packages:
  - "frontend"
  - "packages/*"
  - "services"

allowBuilds:
  "@parcel/watcher": false
  "@swc/core": false
  grpc-tools: true
  sharp: false
  unrs-resolver: false

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
