-- =============================================================================
-- DentiFlow Database Schema
-- Engine  : MySQL 8.4 LTS
-- Strategy: Per-service schemas, clinic_id isolation, outbox per write-service
-- =============================================================================
--
-- ARCHITECTURE OVERVIEW
-- ---------------------
-- This project uses microservices. Each service owns its own MySQL database
-- (schema). Services NEVER share a database or join across schemas at the
-- SQL level. When service A needs data owned by service B, it calls service B
-- via gRPC — not a SQL join.
--
-- CROSS-SERVICE "FOREIGN KEYS"
-- ----------------------------
-- Because DBs are separate, there are no real DB-level FOREIGN KEY constraints
-- between services. You will see columns like:
--     patient_id  CHAR(36)  NOT NULL  COMMENT 'FK to patient_service.patients'
-- The word "FK" in the comment is informational only — it documents the
-- relationship but does NOT enforce anything in the database. Your application
-- code (use-case layer) is responsible for validating that these IDs exist
-- before writing. Within the SAME service/schema, real FOREIGN KEY constraints
-- ARE used (e.g. treatment_acts → visits inside treatment_service).
--
-- SNAPSHOT COLUMNS  (patient_name, doctor_name, assistant_name, etc.)
-- -------------------------------------------------------------------
-- Several tables store a copy of a name or phone number at the time a record
-- is created. These are called "snapshots". Rules:
--   1. Written ONCE at creation — never updated afterwards.
--   2. They allow high-frequency screens (queue, appointment list, invoice)
--      to render without making a gRPC call to another service just for a name.
--   3. If a patient changes their name later, old records intentionally keep
--      the old name — this is correct for medical/financial audit trails.
--   4. If you need the CURRENT name of a patient, call patient_service via gRPC.
--
-- OUTBOX PATTERN
-- --------------
-- Every write-service (appointment, queue, treatment, checkout) has an
-- "outbox" table in its own schema. When a use-case writes a domain record,
-- it ALSO inserts an event row into the outbox — in the SAME DB transaction.
-- A background relay process polls the outbox, publishes pending events to
-- NATS, and marks them published = TRUE. This guarantees that an event is
-- never lost even if NATS is temporarily down at the moment of the write.
--
-- CLINIC_ID ISOLATION
-- -------------------
-- Every domain table has a clinic_id column. All queries MUST include
-- WHERE clinic_id = ? — enforced at the application layer. This isolates
-- data between clinics and prepares the schema for V2 multi-tenant
-- partitioning with zero migration cost.
--
-- ID STRATEGY
-- -----------
-- All primary keys are CHAR(36) UUIDs generated by MySQL's UUID() function.
-- This avoids exposing auto-increment sequences to clients and makes IDs safe
-- to reference across services without coordination.
-- =============================================================================


-- =============================================================================
-- AUTH SERVICE
-- Purpose : Handles login credentials, JWT issuance, and token lifecycle.
--           This is the ONLY service that knows passwords.
--           It does NOT store names, phones, or any profile data.
--           Staff profile data lives in clinic_service.staff_members.
--           Patient profile data lives in patient_service.patients.
-- =============================================================================
CREATE DATABASE IF NOT EXISTS auth_service;
USE auth_service;

-- "users" = login accounts only, not full profiles.
-- One row per (email, clinic) pair. The same real-world person working at two
-- clinics gets two rows — one per clinic — keeping auth scoping clean.
-- The "role" column is used to generate the JWT claim. Display name and phone
-- live in clinic_service.staff_members (staff) or patient_service.patients (patients).
CREATE TABLE users (
  id            CHAR(36)     NOT NULL DEFAULT (UUID()),
  clinic_id     CHAR(36)     NOT NULL,            -- which clinic this login account belongs to
  email         VARCHAR(255) NOT NULL,            -- login credential — NOT a notification contact email
  password_hash VARCHAR(255) NOT NULL,            -- bcrypt hash — plain text is never stored
  role          ENUM(
                  'PATIENT',
                  'SECRETARY',
                  'DENTAL_ASSISTANT',
                  'DOCTOR',
                  'ADMIN'
                )            NOT NULL,
  is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (id),
  -- The same email CAN exist at two different clinics (e.g. a locum doctor),
  -- but must be unique within a single clinic.
  UNIQUE  KEY uq_users_email_clinic (email, clinic_id),
  INDEX   idx_users_clinic          (clinic_id),
  INDEX   idx_users_role            (clinic_id, role)
);

-- Stores hashed refresh tokens. Access tokens (JWT, 15 min TTL) are stateless
-- and not stored here. Refresh tokens are rotated on every use — the old row
-- is marked revoked and a new row is inserted. On logout, the row is revoked.
-- revoked_at NULL  = token is still valid (unless expires_at has passed).
-- revoked_at set   = token has been explicitly invalidated.
CREATE TABLE refresh_tokens (
  id          CHAR(36)     NOT NULL DEFAULT (UUID()),
  user_id     CHAR(36)     NOT NULL,
  clinic_id   CHAR(36)     NOT NULL,
  token_hash  VARCHAR(255) NOT NULL,  -- SHA-256 hash of the raw token string sent to the client
  expires_at  DATETIME     NOT NULL,
  revoked_at  DATETIME         NULL,  -- NULL = still valid; set = invalidated (logout or rotation)
  created_at  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (id),
  UNIQUE  KEY uq_refresh_token_hash  (token_hash),
  INDEX   idx_refresh_tokens_user    (user_id),
  INDEX   idx_refresh_tokens_clinic  (clinic_id),
  -- When a user account is deleted, all their tokens are cleaned up automatically.
  CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);


-- =============================================================================
-- CLINIC SERVICE
-- Purpose : Stores clinic configuration, working hours, and staff assignments.
--           "Staff assignment" = which user belongs to which clinic with which
--           role and what their display name/phone is.
--           clinic_service does NOT handle login — that is auth_service.
-- =============================================================================
CREATE DATABASE IF NOT EXISTS clinic_service;
USE clinic_service;

-- One row per clinic (tenant). At MVP there is one clinic per deployment,
-- but this table is ready for V2 multi-tenant where many clinics share the
-- platform. The "slug" is the URL-safe identifier used in routes like
-- /c/dr-benali-clinic — it is for UX only and is NEVER used for auth decisions.
CREATE TABLE clinics (
  id         CHAR(36)     NOT NULL DEFAULT (UUID()),
  slug       VARCHAR(100) NOT NULL,   -- URL-safe name e.g. "dr-benali-algiers" — UX only, never trusted for auth
  name       VARCHAR(255) NOT NULL,
  phone      VARCHAR(30)      NULL,
  email      VARCHAR(255)     NULL,
  address    TEXT             NULL,
  timezone   VARCHAR(60)  NOT NULL DEFAULT 'Africa/Algiers',  -- used for scheduling and slot calculations
  locale     ENUM('ar','fr','en') NOT NULL DEFAULT 'fr',       -- default UI language for this clinic
  is_active  BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (id),
  UNIQUE KEY uq_clinics_slug (slug)
);

-- Defines when the clinic is open each day of the week.
-- 7 rows per clinic (one per day). If is_closed = TRUE for a day,
-- open_time/close_time are ignored. The appointment service uses this to
-- validate that a requested slot falls within working hours.
CREATE TABLE working_hours (
  id           CHAR(36) NOT NULL DEFAULT (UUID()),
  clinic_id    CHAR(36) NOT NULL,
  day_of_week  TINYINT  NOT NULL COMMENT '0=Sun 1=Mon 2=Tue 3=Wed 4=Thu 5=Fri 6=Sat',
  open_time    TIME         NULL,   -- e.g. '08:30:00' — NULL when is_closed = TRUE
  close_time   TIME         NULL,   -- e.g. '18:00:00'
  is_closed    BOOLEAN  NOT NULL DEFAULT FALSE,

  PRIMARY KEY (id),
  -- Enforces exactly one schedule row per day per clinic.
  UNIQUE KEY uq_working_hours_day (clinic_id, day_of_week),
  INDEX  idx_working_hours_clinic  (clinic_id),
  CONSTRAINT fk_working_hours_clinic FOREIGN KEY (clinic_id) REFERENCES clinics (id) ON DELETE CASCADE
);

-- Bridges auth_service.users to a clinic with a role and a display profile.
-- WHY SEPARATE FROM users?
--   auth_service.users = login/credential entity (email + password hash + role).
--   staff_members      = professional identity entity (name, phone, role at THIS clinic).
--   A doctor who works at two clinics has one users row per clinic in auth_service,
--   and one staff_members row per clinic here. Keeping them separate means auth
--   never needs to know about names, and clinic_service never needs to touch passwords.
CREATE TABLE staff_members (
  id         CHAR(36)     NOT NULL DEFAULT (UUID()),
  clinic_id  CHAR(36)     NOT NULL,
  user_id    CHAR(36)     NOT NULL COMMENT 'FK to auth_service.users',
  role       ENUM('SECRETARY','DENTAL_ASSISTANT','DOCTOR','ADMIN') NOT NULL,
  first_name VARCHAR(100) NOT NULL,
  last_name  VARCHAR(100) NOT NULL,
  phone      VARCHAR(30)      NULL,
  is_active  BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (id),
  UNIQUE KEY uq_staff_user_clinic  (user_id, clinic_id),
  INDEX  idx_staff_clinic          (clinic_id),
  INDEX  idx_staff_role            (clinic_id, role),
  INDEX  idx_staff_name            (clinic_id, last_name, first_name)
);


-- =============================================================================
-- PATIENT SERVICE
-- Purpose : Stores patient demographic records — who they are, not their
--           appointments or treatments (those live in other services).
--           A patient can exist without a login account (walk-in patients).
--           If they self-register online, user_id links to their auth account.
-- =============================================================================
CREATE DATABASE IF NOT EXISTS patient_service;
USE patient_service;

-- A patient record is created the first time the clinic sees them —
-- either when they self-register online (user_id is set) or when the
-- secretary manually creates them for a walk-in (user_id is NULL).
--
-- WHY does email appear here AND in auth_service.users?
--   auth_service email = login credential (used to sign in to the app).
--   patients email     = contact address for WhatsApp/email notifications.
--   Walk-in patients never log in — they have a contact email but no account.
--   Even for online patients these could differ (work email to log in,
--   personal email for clinic reminders). They serve different purposes.
CREATE TABLE patients (
  id            CHAR(36)     NOT NULL DEFAULT (UUID()),
  clinic_id     CHAR(36)     NOT NULL,
  user_id       CHAR(36)         NULL COMMENT 'FK to auth_service.users — NULL for walk-in patients with no login account',
  first_name    VARCHAR(100) NOT NULL,
  last_name     VARCHAR(100) NOT NULL,
  phone         VARCHAR(30)      NULL,   -- used for WhatsApp notifications
  email         VARCHAR(255)     NULL,   -- contact email for notifications — NOT a login credential
  date_of_birth DATE             NULL,
  gender        ENUM('MALE','FEMALE','OTHER') NULL,
  address       TEXT             NULL,
  notes         TEXT             NULL COMMENT 'Internal clinic notes — never shown to patients',
  created_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (id),
  INDEX idx_patients_clinic  (clinic_id),
  INDEX idx_patients_user    (user_id),
  INDEX idx_patients_phone   (clinic_id, phone),                -- for secretary phone-number lookup
  INDEX idx_patients_name    (clinic_id, last_name, first_name) -- for secretary name search
);


-- =============================================================================
-- APPOINTMENT SERVICE
-- Purpose : Manages booking, slot conflict prevention, appointment status,
--           and the real-time waiting room queue.
--           Supports 3 intake channels: ONLINE (patient self-books),
--           WALK_IN (secretary creates on arrival), PHONE (secretary creates
--           during a call). Queue entries track patient journey through
--           the waiting room: ARRIVED → WAITING → IN_CHAIR → DONE.
--           Emits events to NATS via the outbox table.
-- =============================================================================
CREATE DATABASE IF NOT EXISTS appointment_service;
USE appointment_service;

-- SNAPSHOT COLUMNS (patient_name, patient_phone, doctor_name):
--   Copied from patient_service/clinic_service at booking time, never changed.
--   This allows the appointment list and calendar view to render without any
--   gRPC call to another service. If a patient updates their name later,
--   these old records keep the original name — correct for booking history.
--   To get the CURRENT patient name, call patient_service via gRPC.
--
-- created_by:
--   NULL = patient booked themselves online.
--   set  = a secretary or admin created this on behalf of a patient.
--
-- Status flow:
--   PENDING → CONFIRMED → COMPLETED  (normal path)
--   PENDING → CANCELLED              (cancelled before the visit)
--   CONFIRMED → NO_SHOW              (patient did not arrive)
CREATE TABLE appointments (
  id               CHAR(36)     NOT NULL DEFAULT (UUID()),
  clinic_id        CHAR(36)     NOT NULL,
  patient_id       CHAR(36)     NOT NULL COMMENT 'FK to patient_service.patients',
  -- SNAPSHOT: copied from patient record at booking time. Write once, never update.
  patient_name     VARCHAR(255) NOT NULL COMMENT 'Snapshot — write once at booking, never update',
  patient_phone    VARCHAR(30)      NULL COMMENT 'Snapshot — write once at booking, never update',
  doctor_id        CHAR(36)     NOT NULL COMMENT 'FK to auth_service.users (role=DOCTOR)',
  -- SNAPSHOT: copied from clinic_service.staff_members at booking time. Write once, never update.
  doctor_name      VARCHAR(255) NOT NULL COMMENT 'Snapshot — write once at booking, never update',
  scheduled_at     DATETIME     NOT NULL,
  duration_minutes SMALLINT     NOT NULL DEFAULT 30,
  channel          ENUM('ONLINE','WALK_IN','PHONE') NOT NULL,
  status           ENUM(
                     'PENDING',    -- booked, awaiting confirmation
                     'CONFIRMED',  -- secretary confirmed the slot
                     'CANCELLED',  -- cancelled before the visit
                     'NO_SHOW',    -- patient did not arrive
                     'COMPLETED'   -- visit finished
                   )          NOT NULL DEFAULT 'PENDING',
  notes            TEXT           NULL,
  created_by       CHAR(36)       NULL COMMENT 'FK to auth_service.users — NULL = patient self-booked online',
  created_at       DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (id),
  INDEX idx_appointments_clinic      (clinic_id),
  INDEX idx_appointments_patient     (clinic_id, patient_id),
  INDEX idx_appointments_doctor_date (clinic_id, doctor_id, scheduled_at),
  INDEX idx_appointments_status_date (clinic_id, status, scheduled_at)
);

-- Each row = one patient's journey through the waiting room on one visit day.
-- Transition timestamps (arrived_at, called_at, seated_at, completed_at) let
-- you calculate wait time and chair time for V2 analytics.
--
-- SNAPSHOT COLUMNS (patient_name, doctor_name):
--   The waiting room screen is the highest-frequency read in the entire app.
--   Storing names here means it renders with a single query — zero gRPC calls
--   needed to refresh every row on a real-time status update.
--
-- UNIQUE KEY on appointment_id:
--   Prevents the same appointment from being added to the queue twice.
CREATE TABLE queue_entries (
  id               CHAR(36)     NOT NULL DEFAULT (UUID()),
  clinic_id        CHAR(36)     NOT NULL,
  appointment_id   CHAR(36)     NOT NULL COMMENT 'FK to appointment_service.appointments',
  patient_id       CHAR(36)     NOT NULL COMMENT 'FK to patient_service.patients',
  -- SNAPSHOT: copied from the appointment record when the queue entry is created. Write once, never update.
  patient_name     VARCHAR(255) NOT NULL COMMENT 'Snapshot — write once at arrival, never update',
  doctor_id        CHAR(36)     NOT NULL COMMENT 'FK to auth_service.users (role=DOCTOR)',
  -- SNAPSHOT: copied from the appointment record when the queue entry is created. Write once, never update.
  doctor_name      VARCHAR(255) NOT NULL COMMENT 'Snapshot — write once at arrival, never update',
  -- State machine: one direction only — you cannot go backwards.
  status           ENUM(
                     'ARRIVED',   -- patient checked in at reception
                     'WAITING',   -- called by assistant, waiting for chair
                     'IN_CHAIR',  -- currently being treated
                     'DONE'       -- treatment finished, ready for checkout
                   )          NOT NULL DEFAULT 'ARRIVED',
  -- Each timestamp is set once when the status transitions to that state, then never changed.
  arrived_at       DATETIME  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  called_at        DATETIME      NULL COMMENT 'Set when status → WAITING',
  seated_at        DATETIME      NULL COMMENT 'Set when status → IN_CHAIR',
  completed_at     DATETIME      NULL COMMENT 'Set when status → DONE',
  updated_at       DATETIME  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (id),
  UNIQUE KEY uq_queue_appointment   (appointment_id),         -- one queue entry per appointment
  INDEX idx_queue_clinic_status     (clinic_id, status),      -- main waiting room query
  INDEX idx_queue_clinic_doctor     (clinic_id, doctor_id, status),  -- doctor's own queue view
  INDEX idx_queue_clinic_date       (clinic_id, arrived_at),  -- daily queue history
  -- Real FK within the same service schema — enforced at DB level.
  CONSTRAINT fk_queue_entries_appointment FOREIGN KEY (appointment_id) REFERENCES appointments (id) ON DELETE CASCADE
);

-- OUTBOX: same pattern used in every write-service.
-- Inserted in the same transaction as the domain write — guarantees events
-- are never lost if NATS is down. A relay process publishes and marks rows done.
-- Handles events from both appointments and queue operations.
CREATE TABLE outbox (
  id          CHAR(36)     NOT NULL DEFAULT (UUID()),
  event_type  VARCHAR(100) NOT NULL,  -- e.g. 'appointment.confirmed', 'appointment.cancelled', 'queue.status.updated'
  payload     JSON         NOT NULL,  -- full event consumed by notification-service, audit-service, etc. Queue events include clinic_id for SSE fanout.
  published   BOOLEAN      NOT NULL DEFAULT FALSE,
  created_at  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (id),
  -- Relay polls WHERE published = FALSE ORDER BY created_at — index makes it fast.
  INDEX idx_outbox_unpublished (published, created_at)
);


-- =============================================================================
-- TREATMENT SERVICE
-- Purpose : Manages the act catalog (procedure list) and clinical visit records.
--           A visit is opened when a patient enters the chair. The dental
--           assistant adds treatment acts (procedures performed). The doctor
--           reviews and confirms. Once CONFIRMED the visit moves to CLOSED and
--           checkout_service creates an invoice from the visit total.
-- =============================================================================
CREATE DATABASE IF NOT EXISTS treatment_service;
USE treatment_service;

-- The admin-managed list of billable procedures at this clinic.
-- Each act has trilingual names (ar/fr/en) because the UI is multilingual.
-- is_active = FALSE hides the act from the assistant UI (soft-delete).
-- IMPORTANT: When an assistant records an act on a visit, unit_price is copied
-- from default_price at that moment (another snapshot). Changing the catalog
-- price later does NOT retroactively change historical treatment records.
CREATE TABLE act_catalog (
  id            CHAR(36)       NOT NULL DEFAULT (UUID()),
  clinic_id     CHAR(36)       NOT NULL,
  code          VARCHAR(50)    NOT NULL,  -- admin-defined code e.g. "CONSULT", "EXTRACT-1"
  name_ar       VARCHAR(255)   NOT NULL,  -- Arabic name shown to Arabic-locale users
  name_fr       VARCHAR(255)   NOT NULL,  -- French name
  name_en       VARCHAR(255)   NOT NULL,  -- English name
  default_price DECIMAL(10,2)  NOT NULL DEFAULT 0.00,
  is_active     BOOLEAN        NOT NULL DEFAULT TRUE,  -- FALSE = hidden from assistant UI (soft-delete)
  created_at    DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (id),
  UNIQUE KEY uq_act_code_clinic (clinic_id, code),  -- code must be unique per clinic
  INDEX  idx_act_catalog_clinic (clinic_id)
);

-- One visit row is created per appointment when the patient moves to IN_CHAIR.
-- It aggregates all treatment_acts and tracks the confirmation workflow:
--   OPEN → assistant enters acts
--   CONFIRMED → doctor has reviewed and signed off
--   CLOSED → handed to checkout, no further changes allowed
CREATE TABLE visits (
  id             CHAR(36)       NOT NULL DEFAULT (UUID()),
  clinic_id      CHAR(36)       NOT NULL,
  appointment_id CHAR(36)       NOT NULL COMMENT 'FK to appointment_service.appointments',
  patient_id     CHAR(36)       NOT NULL COMMENT 'FK to patient_service.patients',
  -- SNAPSHOT: copied when visit is opened. Write once, never update.
  patient_name   VARCHAR(255)   NOT NULL COMMENT 'Snapshot — write once when visit opens, never update',
  doctor_id      CHAR(36)       NOT NULL COMMENT 'FK to auth_service.users (role=DOCTOR)',
  -- SNAPSHOT: copied when visit is opened. Write once, never update.
  doctor_name    VARCHAR(255)   NOT NULL COMMENT 'Snapshot — write once when visit opens, never update',
  assistant_id   CHAR(36)           NULL COMMENT 'FK to auth_service.users (role=DENTAL_ASSISTANT)',
  -- SNAPSHOT: set when an assistant is assigned. NULL until then. Write once, never update.
  assistant_name VARCHAR(255)       NULL COMMENT 'Snapshot — set once when assistant assigned, never update',
  status         ENUM(
                   'OPEN',       -- assistant is entering acts
                   'CONFIRMED',  -- doctor reviewed and signed off
                   'CLOSED'      -- handed to checkout, immutable
                 )               NOT NULL DEFAULT 'OPEN',
  total_amount   DECIMAL(10,2)  NOT NULL DEFAULT 0.00,  -- recalculated by use-case on every act change
  confirmed_at   DATETIME           NULL,
  -- confirmed_by may differ from doctor_id (e.g. covering doctor)
  confirmed_by   CHAR(36)           NULL COMMENT 'FK to auth_service.users (role=DOCTOR) — may differ from doctor_id',
  created_at     DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (id),
  UNIQUE KEY uq_visit_appointment   (appointment_id),
  INDEX idx_visits_clinic           (clinic_id),
  INDEX idx_visits_patient          (clinic_id, patient_id),
  INDEX idx_visits_doctor           (clinic_id, doctor_id),
  INDEX idx_visits_status           (clinic_id, status)
);

-- Individual procedure lines recorded during a visit.
-- Each row = one procedure performed (optionally on a specific tooth).
-- tooth_fdi uses the FDI two-digit notation:
--   Upper-right: 11–18 | Upper-left: 21–28
--   Lower-left:  31–38 | Lower-right: 41–48
--   NULL = procedure is not tooth-specific (e.g. a consultation fee).
-- unit_price is a SNAPSHOT copied from act_catalog.default_price at entry time.
-- Changing the catalog price later does NOT affect this historical line.
CREATE TABLE treatment_acts (
  id              CHAR(36)       NOT NULL DEFAULT (UUID()),
  clinic_id       CHAR(36)       NOT NULL,
  visit_id        CHAR(36)       NOT NULL,
  act_catalog_id  CHAR(36)       NOT NULL,
  tooth_fdi       VARCHAR(10)        NULL COMMENT 'FDI notation e.g. "11" = upper-right central incisor. NULL = not tooth-specific.',
  quantity        TINYINT        NOT NULL DEFAULT 1,
  -- SNAPSHOT: copied from act_catalog.default_price at entry time. Write once, never update.
  unit_price      DECIMAL(10,2)  NOT NULL COMMENT 'Snapshot of price at entry time — catalog changes do not affect this',
  notes           TEXT               NULL,
  entered_by      CHAR(36)       NOT NULL COMMENT 'FK to auth_service.users — the assistant or doctor who entered this act',
  created_at      DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (id),
  INDEX idx_treatment_acts_visit   (visit_id),
  INDEX idx_treatment_acts_clinic  (clinic_id),
  -- Real FK within the same service schema — enforced at DB level.
  CONSTRAINT fk_treatment_acts_visit       FOREIGN KEY (visit_id)       REFERENCES visits      (id) ON DELETE CASCADE,
  CONSTRAINT fk_treatment_acts_act_catalog FOREIGN KEY (act_catalog_id) REFERENCES act_catalog (id)
);

-- See outbox explanation above — same pattern, same purpose.
CREATE TABLE outbox (
  id          CHAR(36)     NOT NULL DEFAULT (UUID()),
  event_type  VARCHAR(100) NOT NULL,  -- e.g. 'visit.confirmed', 'visit.closed'
  payload     JSON         NOT NULL,
  published   BOOLEAN      NOT NULL DEFAULT FALSE,
  created_at  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (id),
  INDEX idx_outbox_unpublished (published, created_at)
);


-- =============================================================================
-- CHECKOUT SERVICE
-- Purpose : Handles invoicing, payment recording, and balance carry-forward.
--           A visit.closed NATS event triggers invoice creation here.
--           Partial payments are supported — the unpaid balance is tracked in
--           patient_balances and carried forward to the patient's next visit.
-- =============================================================================
CREATE DATABASE IF NOT EXISTS checkout_service;
USE checkout_service;

-- One invoice per visit. Created automatically when a visit moves to CLOSED.
-- balance_due is a VIRTUAL GENERATED COLUMN — MySQL computes it automatically
-- as (total_amount - paid_amount). You never write to it; it always reflects
-- the current arithmetic. Status: PENDING → PARTIAL → PAID.
CREATE TABLE invoices (
  id            CHAR(36)       NOT NULL DEFAULT (UUID()),
  clinic_id     CHAR(36)       NOT NULL,
  visit_id      CHAR(36)       NOT NULL COMMENT 'FK to treatment_service.visits',
  patient_id    CHAR(36)       NOT NULL COMMENT 'FK to patient_service.patients',
  -- SNAPSHOT: copied when invoice is created. Write once, never update.
  patient_name  VARCHAR(255)   NOT NULL COMMENT 'Snapshot — write once at invoice creation, never update',
  total_amount  DECIMAL(10,2)  NOT NULL,
  paid_amount   DECIMAL(10,2)  NOT NULL DEFAULT 0.00,
  balance_due   DECIMAL(10,2)  NOT NULL GENERATED ALWAYS AS (total_amount - paid_amount) VIRTUAL,
  status        ENUM('PENDING','PARTIAL','PAID') NOT NULL DEFAULT 'PENDING',
  created_at    DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (id),
  UNIQUE KEY uq_invoice_visit      (visit_id),
  INDEX idx_invoices_clinic        (clinic_id),
  INDEX idx_invoices_patient       (clinic_id, patient_id),
  INDEX idx_invoices_status        (clinic_id, status)
);

-- Each payment transaction recorded against an invoice.
-- Multiple rows can exist per invoice (partial payment at visit, remainder paid later).
-- The use-case keeps invoices.paid_amount in sync with the sum of payment rows.
-- No updated_at — payments are immutable financial records. Never update a payment row.
CREATE TABLE payments (
  id          CHAR(36)       NOT NULL DEFAULT (UUID()),
  clinic_id   CHAR(36)       NOT NULL,
  invoice_id  CHAR(36)       NOT NULL,
  amount      DECIMAL(10,2)  NOT NULL,
  method      ENUM('CASH','CARD','BANK_TRANSFER') NOT NULL DEFAULT 'CASH',
  notes       TEXT               NULL,
  created_by  CHAR(36)       NOT NULL COMMENT 'FK to auth_service.users — secretary who recorded the payment',
  created_at  DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP,  -- no updated_at: payments are immutable

  PRIMARY KEY (id),
  INDEX idx_payments_invoice  (invoice_id),
  INDEX idx_payments_clinic   (clinic_id),
  -- ON DELETE RESTRICT: you cannot delete an invoice that has payments against it.
  CONSTRAINT fk_payments_invoice FOREIGN KEY (invoice_id) REFERENCES invoices (id) ON DELETE RESTRICT
);

-- Running balance per patient per clinic.
-- Exactly ONE row per (patient, clinic) pair — enforced by the unique key.
-- The use-case upserts this row on every new invoice or payment.
-- balance < 0 : patient owes money (debt carry-forward to next visit)
-- balance > 0 : patient has credit (overpaid, to be applied to next invoice)
-- balance = 0 : fully settled
CREATE TABLE patient_balances (
  id          CHAR(36)       NOT NULL DEFAULT (UUID()),
  clinic_id   CHAR(36)       NOT NULL,
  patient_id  CHAR(36)       NOT NULL COMMENT 'FK to patient_service.patients',
  balance     DECIMAL(10,2)  NOT NULL DEFAULT 0.00 COMMENT 'Negative = owes clinic | Positive = patient has credit',
  updated_at  DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (id),
  UNIQUE KEY uq_balance_patient_clinic (patient_id, clinic_id),
  INDEX idx_patient_balances_clinic    (clinic_id)
);

-- See outbox explanation above — same pattern, same purpose.
CREATE TABLE outbox (
  id          CHAR(36)     NOT NULL DEFAULT (UUID()),
  event_type  VARCHAR(100) NOT NULL,  -- e.g. 'invoice.created', 'payment.recorded'
  payload     JSON         NOT NULL,
  published   BOOLEAN      NOT NULL DEFAULT FALSE,
  created_at  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (id),
  INDEX idx_outbox_unpublished (published, created_at)
);


-- =============================================================================
-- NOTIFICATION SERVICE
-- Purpose : Dispatches WhatsApp and email notifications. This service is a
--           pure NATS subscriber — it reacts to events from other services
--           (e.g. appointment.confirmed → send WhatsApp message to patient).
--           It has no gRPC endpoint; it only listens and dispatches.
--           notification_logs is the delivery audit trail for debugging and retries.
-- =============================================================================
CREATE DATABASE IF NOT EXISTS notification_service;
USE notification_service;

-- Every notification attempt is logged here regardless of success or failure.
-- sent_at NULL + status FAILED → error_message explains why it failed.
-- recipient is a snapshot of the actual phone/email used at send time.
CREATE TABLE notification_logs (
  id               CHAR(36)     NOT NULL DEFAULT (UUID()),
  clinic_id        CHAR(36)     NOT NULL,
  patient_id       CHAR(36)         NULL COMMENT 'FK to patient_service.patients',
  appointment_id   CHAR(36)         NULL COMMENT 'FK to appointment_service.appointments',
  type             ENUM(
                     'APPOINTMENT_CONFIRMATION',  -- sent when appointment → CONFIRMED
                     'APPOINTMENT_REMINDER',       -- sent ~24h before scheduled_at
                     'APPOINTMENT_CANCELLATION'    -- sent when appointment → CANCELLED
                   )            NOT NULL,
  channel          ENUM('WHATSAPP','EMAIL') NOT NULL,
  recipient        VARCHAR(255) NOT NULL COMMENT 'Actual phone or email used — snapshot at send time',
  status           ENUM('PENDING','SENT','FAILED') NOT NULL DEFAULT 'PENDING',
  error_message    TEXT             NULL,  -- populated when status = FAILED (e.g. WhatsApp API error)
  sent_at          DATETIME         NULL,  -- NULL until the message is successfully delivered
  created_at       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (id),
  INDEX idx_notification_logs_clinic       (clinic_id),
  INDEX idx_notification_logs_appointment  (appointment_id),
  INDEX idx_notification_logs_status       (status, created_at)
);


-- =============================================================================
-- AUDIT SERVICE  (append-only — NO UPDATE, NO DELETE ever)
-- Purpose : Immutable compliance log of all access and mutations to patient
--           data. Required by PDPC (Algeria), Law 09-08/CNDP (Morocco),
--           INPDP (Tunisia), and GDPR. Every time patient data is viewed or
--           changed anywhere in the system, the acting service emits a NATS
--           event and this service appends a row here.
--
-- CRITICAL RULES — do NOT break these:
--   1. Never run UPDATE on this table.
--   2. Never run DELETE on this table.
--   3. No FOREIGN KEY constraints — this store must survive even if other
--      services drop or rename their tables in the future.
--   4. The full event payload is stored in JSON so a compliance officer
--      can reconstruct the exact state of data at any point in time.
-- =============================================================================
CREATE DATABASE IF NOT EXISTS audit_service;
USE audit_service;

CREATE TABLE audit_events (
  id           CHAR(36)     NOT NULL DEFAULT (UUID()),
  clinic_id    CHAR(36)     NOT NULL,
  user_id      CHAR(36)         NULL COMMENT 'The user who triggered the action. NULL for automated system events.',
  -- event_type examples: 'patient.record.viewed', 'treatment.act.created',
  --                      'appointment.cancelled', 'user.login', 'user.logout'
  event_type   VARCHAR(100) NOT NULL,
  -- entity_type + entity_id identify WHAT was affected.
  -- Examples: entity_type='patient', entity_type='appointment', entity_type='visit'
  entity_type  VARCHAR(100) NOT NULL,
  entity_id    CHAR(36)     NOT NULL,
  -- Full snapshot of the event data at the moment it occurred.
  -- Stored as JSON so no schema migration is needed when event shapes evolve.
  payload      JSON         NOT NULL,
  created_at   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (id),
  INDEX idx_audit_clinic  (clinic_id, created_at),              -- all events for a clinic in time order
  INDEX idx_audit_entity  (clinic_id, entity_type, entity_id),  -- all events for a specific record
  INDEX idx_audit_user    (clinic_id, user_id, created_at)       -- all actions by a specific user
  -- NO foreign keys intentionally — audit_service must be fully independent of all other schemas.
);
