export const PATIENT_GRPC_CLIENT = "PATIENT_GRPC_CLIENT";
export const CLINIC_GRPC_CLIENT = "CLINIC_GRPC_CLIENT";
export const PATIENT_SERVICE_CLIENT = Symbol("PATIENT_SERVICE_CLIENT");
export const CLINIC_SERVICE_CLIENT = Symbol("CLINIC_SERVICE_CLIENT");
