import type {DentalAct} from "../entities";

export const TREATMENT_ACTS: DentalAct[] = [
  {
    id: "a1",
    name: "Consultation",
    label: "Consultation",
    icon: "Stethoscope",
    category: "GENERAL",
    price: 50,
    groupableTeeth: false,
    affectsTooth: false,
    defaultStatus: "planned",
    colorHex: "#64748b",
  },
  {
    id: "a2",
    name: "Panoramic X-Ray",
    label: "Panoramic X-Ray",
    icon: "Scan",
    category: "RADIOGRAPHY",
    price: 80,
    groupableTeeth: false,
    affectsTooth: false,
    defaultStatus: "planned",
    colorHex: "#64748b",
  },
  {
    id: "a3",
    name: "Scaling and Polishing",
    label: "Scaling and Polishing",
    icon: "Sparkles",
    category: "PREVENTIVE",
    price: 120,
    groupableTeeth: true,
    affectsTooth: false,
    defaultStatus: "planned",
    colorHex: "#64748b",
  },
  {
    id: "a4",
    name: "Fluoride Treatment",
    label: "Fluoride Treatment",
    icon: "Shield",
    category: "PREVENTIVE",
    price: 60,
    groupableTeeth: true,
    affectsTooth: false,
    defaultStatus: "planned",
    colorHex: "#64748b",
  },
  {
    id: "a5",
    name: "Composite Filling (1 Surface)",
    label: "Composite Filling (1 Surface)",
    icon: "CircleDot",
    category: "RESTORATIVE",
    price: 80,
    groupableTeeth: false,
    affectsTooth: true,
    defaultStatus: "planned",
    colorHex: "#22c55e",
  },
  {
    id: "a6",
    name: "Composite Filling (2 Surfaces)",
    label: "Composite Filling (2 Surfaces)",
    icon: "CircleDot",
    category: "RESTORATIVE",
    price: 120,
    groupableTeeth: false,
    affectsTooth: true,
    defaultStatus: "planned",
    colorHex: "#14b8a6",
  },
  {
    id: "a7",
    name: "Composite Filling (3+ Surfaces)",
    label: "Composite Filling (3+ Surfaces)",
    icon: "CircleDot",
    category: "RESTORATIVE",
    price: 160,
    groupableTeeth: false,
    affectsTooth: true,
    defaultStatus: "planned",
    colorHex: "#06b6d4",
  },
  {
    id: "a8",
    name: "Root Canal Treatment (Anterior)",
    label: "Root Canal Treatment (Anterior)",
    icon: "Activity",
    category: "ENDODONTICS",
    price: 250,
    groupableTeeth: false,
    affectsTooth: true,
    defaultStatus: "planned",
    colorHex: "#f59e0b",
  },
  {
    id: "a9",
    name: "Root Canal Treatment (Premolar)",
    label: "Root Canal Treatment (Premolar)",
    icon: "Activity",
    category: "ENDODONTICS",
    price: 350,
    groupableTeeth: false,
    affectsTooth: true,
    defaultStatus: "planned",
    colorHex: "#f97316",
  },
  {
    id: "a10",
    name: "Root Canal Treatment (Molar)",
    label: "Root Canal Treatment (Molar)",
    icon: "Activity",
    category: "ENDODONTICS",
    price: 450,
    groupableTeeth: false,
    affectsTooth: true,
    defaultStatus: "planned",
    colorHex: "#fb7185",
  },
  {
    id: "a11",
    name: "Simple Extraction",
    label: "Simple Extraction",
    icon: "X",
    category: "SURGERY",
    price: 100,
    groupableTeeth: false,
    visualType: "extraction",
    affectsTooth: true,
    defaultStatus: "planned",
    colorHex: "#ef4444",
  },
  {
    id: "a12",
    name: "Surgical Extraction",
    label: "Surgical Extraction",
    icon: "X",
    category: "SURGERY",
    price: 250,
    groupableTeeth: false,
    visualType: "extraction",
    affectsTooth: true,
    defaultStatus: "planned",
    colorHex: "#f43f5e",
  },
  {
    id: "a13",
    name: "Wisdom Tooth Extraction",
    label: "Wisdom Tooth Extraction",
    icon: "X",
    category: "SURGERY",
    price: 350,
    groupableTeeth: false,
    visualType: "extraction",
    affectsTooth: true,
    defaultStatus: "planned",
    colorHex: "#d946ef",
  },
  {
    id: "a14",
    name: "Ceramic Crown",
    label: "Ceramic Crown",
    icon: "Crown",
    category: "PROSTHETICS",
    price: 600,
    groupableTeeth: false,
    visualType: "crown",
    affectsTooth: true,
    defaultStatus: "planned",
    colorHex: "#eab308",
  },
  {
    id: "a15",
    name: "Zirconia Crown",
    label: "Zirconia Crown",
    icon: "Crown",
    category: "PROSTHETICS",
    price: 800,
    groupableTeeth: false,
    visualType: "crown",
    affectsTooth: true,
    defaultStatus: "planned",
    colorHex: "#84cc16",
  },
  {
    id: "a16",
    name: "Temporary Crown",
    label: "Temporary Crown",
    icon: "Crown",
    category: "PROSTHETICS",
    price: 150,
    groupableTeeth: false,
    visualType: "crown",
    affectsTooth: true,
    defaultStatus: "planned",
    colorHex: "#facc15",
  },
  {
    id: "a17",
    name: "Dental Implant Placement",
    label: "Dental Implant Placement",
    icon: "Anchor",
    category: "SURGERY",
    price: 1200,
    groupableTeeth: false,
    visualType: "implant",
    affectsTooth: true,
    defaultStatus: "planned",
    colorHex: "#38bdf8",
  },
  {
    id: "a18",
    name: "Bone Grafting",
    label: "Bone Grafting",
    icon: "Bone",
    category: "SURGERY",
    price: 400,
    groupableTeeth: false,
    visualType: "graft",
    affectsTooth: true,
    defaultStatus: "planned",
    colorHex: "#c084fc",
  },
  {
    id: "a19",
    name: "Teeth Whitening (In-Office)",
    label: "Teeth Whitening (In-Office)",
    icon: "Sun",
    category: "AESTHETIC",
    price: 300,
    groupableTeeth: true,
    affectsTooth: false,
    defaultStatus: "planned",
    colorHex: "#64748b",
  },
  {
    id: "a20",
    name: "Orthodontic Consultation",
    label: "Orthodontic Consultation",
    icon: "GitCommitHorizontal",
    category: "ORTHODONTICS",
    price: 80,
    groupableTeeth: false,
    affectsTooth: false,
    defaultStatus: "planned",
    colorHex: "#64748b",
  },
];
