export const VISIT_WORKFLOW_REPOSITORY = Symbol("VISIT_WORKFLOW_REPOSITORY");
export const TREATMENT_REPOSITORY = Symbol("TREATMENT_REPOSITORY");
export const OUTBOX_REPOSITORY = Symbol("OUTBOX_REPOSITORY");
