export const ACT_CATALOG_REPOSITORY = Symbol("ACT_CATALOG_REPOSITORY");
export const VISIT_REPOSITORY = Symbol("VISIT_REPOSITORY");
export const TREATMENT_ACT_REPOSITORY = Symbol("TREATMENT_ACT_REPOSITORY");
export const TREATMENT_PLAN_REPOSITORY = Symbol("TREATMENT_PLAN_REPOSITORY");
export const OUTBOX_REPOSITORY = Symbol("OUTBOX_REPOSITORY");
