// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.7
//   protoc               v3.19.1
// source: appointment.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { handleUnaryCall, UntypedServiceImplementation } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "appointment";

export interface AppointmentReply {
  id: string;
  clinicId: string;
  patientId: string;
  patientName: string;
  patientPhone: string;
  doctorId: string;
  doctorName: string;
  startAt: string;
  endAt: string;
  isEmergency: boolean;
  type: string;
  channel: string;
  status: string;
  notes: string;
  cancelledAt: string;
  cancellationReason: string;
  createdBy: string;
  createdAt: string;
  updatedAt: string;
}

export interface AppointmentsListReply {
  appointments: AppointmentReply[];
  total: number;
}

export interface GetAppointmentRequest {
  id: string;
}

export interface ListAppointmentsRequest {
  clinicId: string;
  page?: number | undefined;
  limit?: number | undefined;
  startDate?: string | undefined;
  endDate?: string | undefined;
  doctorId?: string | undefined;
  status?: string | undefined;
}

export interface CreateAppointmentRequest {
  clinicId: string;
  patientId: string;
  patientName: string;
  patientPhone?: string | undefined;
  doctorId: string;
  doctorName: string;
  startAt: string;
  endAt: string;
  isEmergency: boolean;
  type?: string | undefined;
  channel: string;
  status?: string | undefined;
  notes?: string | undefined;
  createdBy?: string | undefined;
}

export interface UpdateAppointmentRequest {
  appointmentId: string;
  patientId?: string | undefined;
  patientName?: string | undefined;
  patientPhone?: string | undefined;
  doctorId?: string | undefined;
  doctorName?: string | undefined;
  startAt?: string | undefined;
  endAt?: string | undefined;
  isEmergency?: boolean | undefined;
  type?: string | undefined;
  channel?: string | undefined;
  status?: string | undefined;
  notes?: string | undefined;
  cancelledAt?: string | undefined;
  cancellationReason?: string | undefined;
}

export interface UpdateAppointmentTimingRequest {
  appointmentId: string;
  doctorId: string;
  doctorName?: string | undefined;
  newStartAt: string;
  newEndAt: string;
}

export interface CheckAppointmentConflictsRequest {
  clinicId?: string | undefined;
  doctorId: string;
  startAt: string;
  endAt: string;
  excludeStatus?: string | undefined;
  excludeAppointmentId?: string | undefined;
}

export interface ConflictReply {
  hasConflict: boolean;
}

export interface QueueEntryReply {
  id: string;
  clinicId: string;
  appointmentId: string;
  patientId: string;
  patientName: string;
  patientPhone: string;
  doctorId: string;
  doctorName: string;
  appointmentType: string;
  status: string;
  priority: string;
  queueNotes: string;
  arrivedAt: string;
  calledAt: string;
  seatedAt: string;
  completedAt: string;
  updatedAt: string;
}

export interface QueueEntriesListReply {
  queueEntries: QueueEntryReply[];
}

export interface ListQueueEntriesRequest {
  clinicId: string;
}

export interface GetQueueEntryRequest {
  id: string;
}

export interface CheckInPatientRequest {
  clinicId: string;
  appointmentId: string;
  patientId: string;
  patientName: string;
  patientPhone?: string | undefined;
  doctorId: string;
  doctorName: string;
  appointmentType?: string | undefined;
  priority?: string | undefined;
  queueNotes?: string | undefined;
  arrivedAt?: string | undefined;
}

export interface UpdateQueueStatusRequest {
  queueEntryId: string;
  status: string;
  correctionReason?: string | undefined;
}

export interface UpdateQueueNotesRequest {
  queueEntryId: string;
  queueNotes?: string | undefined;
}

export const APPOINTMENT_PACKAGE_NAME = "appointment";

function createBaseAppointmentReply(): AppointmentReply {
  return {
    id: "",
    clinicId: "",
    patientId: "",
    patientName: "",
    patientPhone: "",
    doctorId: "",
    doctorName: "",
    startAt: "",
    endAt: "",
    isEmergency: false,
    type: "",
    channel: "",
    status: "",
    notes: "",
    cancelledAt: "",
    cancellationReason: "",
    createdBy: "",
    createdAt: "",
    updatedAt: "",
  };
}

export const AppointmentReply: MessageFns<AppointmentReply> = {
  encode(message: AppointmentReply, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.clinicId !== "") {
      writer.uint32(18).string(message.clinicId);
    }
    if (message.patientId !== "") {
      writer.uint32(26).string(message.patientId);
    }
    if (message.patientName !== "") {
      writer.uint32(34).string(message.patientName);
    }
    if (message.patientPhone !== "") {
      writer.uint32(42).string(message.patientPhone);
    }
    if (message.doctorId !== "") {
      writer.uint32(50).string(message.doctorId);
    }
    if (message.doctorName !== "") {
      writer.uint32(58).string(message.doctorName);
    }
    if (message.startAt !== "") {
      writer.uint32(66).string(message.startAt);
    }
    if (message.endAt !== "") {
      writer.uint32(74).string(message.endAt);
    }
    if (message.isEmergency !== false) {
      writer.uint32(80).bool(message.isEmergency);
    }
    if (message.type !== "") {
      writer.uint32(90).string(message.type);
    }
    if (message.channel !== "") {
      writer.uint32(98).string(message.channel);
    }
    if (message.status !== "") {
      writer.uint32(106).string(message.status);
    }
    if (message.notes !== "") {
      writer.uint32(114).string(message.notes);
    }
    if (message.cancelledAt !== "") {
      writer.uint32(122).string(message.cancelledAt);
    }
    if (message.cancellationReason !== "") {
      writer.uint32(130).string(message.cancellationReason);
    }
    if (message.createdBy !== "") {
      writer.uint32(138).string(message.createdBy);
    }
    if (message.createdAt !== "") {
      writer.uint32(146).string(message.createdAt);
    }
    if (message.updatedAt !== "") {
      writer.uint32(154).string(message.updatedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AppointmentReply {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAppointmentReply();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.clinicId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.patientId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.patientName = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.patientPhone = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.doctorId = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.doctorName = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.startAt = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.endAt = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.isEmergency = reader.bool();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.channel = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.notes = reader.string();
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.cancelledAt = reader.string();
          continue;
        }
        case 16: {
          if (tag !== 130) {
            break;
          }

          message.cancellationReason = reader.string();
          continue;
        }
        case 17: {
          if (tag !== 138) {
            break;
          }

          message.createdBy = reader.string();
          continue;
        }
        case 18: {
          if (tag !== 146) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
        case 19: {
          if (tag !== 154) {
            break;
          }

          message.updatedAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseAppointmentsListReply(): AppointmentsListReply {
  return { appointments: [], total: 0 };
}

export const AppointmentsListReply: MessageFns<AppointmentsListReply> = {
  encode(message: AppointmentsListReply, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.appointments) {
      AppointmentReply.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.total !== 0) {
      writer.uint32(16).int32(message.total);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AppointmentsListReply {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAppointmentsListReply();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.appointments.push(AppointmentReply.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.total = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetAppointmentRequest(): GetAppointmentRequest {
  return { id: "" };
}

export const GetAppointmentRequest: MessageFns<GetAppointmentRequest> = {
  encode(message: GetAppointmentRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetAppointmentRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetAppointmentRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseListAppointmentsRequest(): ListAppointmentsRequest {
  return { clinicId: "" };
}

export const ListAppointmentsRequest: MessageFns<ListAppointmentsRequest> = {
  encode(message: ListAppointmentsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.clinicId !== "") {
      writer.uint32(10).string(message.clinicId);
    }
    if (message.page !== undefined) {
      writer.uint32(16).int32(message.page);
    }
    if (message.limit !== undefined) {
      writer.uint32(24).int32(message.limit);
    }
    if (message.startDate !== undefined) {
      writer.uint32(34).string(message.startDate);
    }
    if (message.endDate !== undefined) {
      writer.uint32(42).string(message.endDate);
    }
    if (message.doctorId !== undefined) {
      writer.uint32(50).string(message.doctorId);
    }
    if (message.status !== undefined) {
      writer.uint32(58).string(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListAppointmentsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListAppointmentsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.clinicId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.page = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.startDate = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.endDate = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.doctorId = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.status = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCreateAppointmentRequest(): CreateAppointmentRequest {
  return {
    clinicId: "",
    patientId: "",
    patientName: "",
    doctorId: "",
    doctorName: "",
    startAt: "",
    endAt: "",
    isEmergency: false,
    channel: "",
  };
}

export const CreateAppointmentRequest: MessageFns<CreateAppointmentRequest> = {
  encode(message: CreateAppointmentRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.clinicId !== "") {
      writer.uint32(10).string(message.clinicId);
    }
    if (message.patientId !== "") {
      writer.uint32(18).string(message.patientId);
    }
    if (message.patientName !== "") {
      writer.uint32(26).string(message.patientName);
    }
    if (message.patientPhone !== undefined) {
      writer.uint32(34).string(message.patientPhone);
    }
    if (message.doctorId !== "") {
      writer.uint32(42).string(message.doctorId);
    }
    if (message.doctorName !== "") {
      writer.uint32(50).string(message.doctorName);
    }
    if (message.startAt !== "") {
      writer.uint32(58).string(message.startAt);
    }
    if (message.endAt !== "") {
      writer.uint32(66).string(message.endAt);
    }
    if (message.isEmergency !== false) {
      writer.uint32(72).bool(message.isEmergency);
    }
    if (message.type !== undefined) {
      writer.uint32(82).string(message.type);
    }
    if (message.channel !== "") {
      writer.uint32(90).string(message.channel);
    }
    if (message.status !== undefined) {
      writer.uint32(98).string(message.status);
    }
    if (message.notes !== undefined) {
      writer.uint32(106).string(message.notes);
    }
    if (message.createdBy !== undefined) {
      writer.uint32(114).string(message.createdBy);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateAppointmentRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateAppointmentRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.clinicId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.patientId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.patientName = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.patientPhone = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.doctorId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.doctorName = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.startAt = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.endAt = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.isEmergency = reader.bool();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.channel = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.notes = reader.string();
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.createdBy = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseUpdateAppointmentRequest(): UpdateAppointmentRequest {
  return { appointmentId: "" };
}

export const UpdateAppointmentRequest: MessageFns<UpdateAppointmentRequest> = {
  encode(message: UpdateAppointmentRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.appointmentId !== "") {
      writer.uint32(10).string(message.appointmentId);
    }
    if (message.patientId !== undefined) {
      writer.uint32(18).string(message.patientId);
    }
    if (message.patientName !== undefined) {
      writer.uint32(26).string(message.patientName);
    }
    if (message.patientPhone !== undefined) {
      writer.uint32(34).string(message.patientPhone);
    }
    if (message.doctorId !== undefined) {
      writer.uint32(42).string(message.doctorId);
    }
    if (message.doctorName !== undefined) {
      writer.uint32(50).string(message.doctorName);
    }
    if (message.startAt !== undefined) {
      writer.uint32(58).string(message.startAt);
    }
    if (message.endAt !== undefined) {
      writer.uint32(66).string(message.endAt);
    }
    if (message.isEmergency !== undefined) {
      writer.uint32(72).bool(message.isEmergency);
    }
    if (message.type !== undefined) {
      writer.uint32(82).string(message.type);
    }
    if (message.channel !== undefined) {
      writer.uint32(90).string(message.channel);
    }
    if (message.status !== undefined) {
      writer.uint32(98).string(message.status);
    }
    if (message.notes !== undefined) {
      writer.uint32(106).string(message.notes);
    }
    if (message.cancelledAt !== undefined) {
      writer.uint32(114).string(message.cancelledAt);
    }
    if (message.cancellationReason !== undefined) {
      writer.uint32(122).string(message.cancellationReason);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateAppointmentRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateAppointmentRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.appointmentId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.patientId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.patientName = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.patientPhone = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.doctorId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.doctorName = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.startAt = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.endAt = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.isEmergency = reader.bool();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.channel = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.notes = reader.string();
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.cancelledAt = reader.string();
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.cancellationReason = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseUpdateAppointmentTimingRequest(): UpdateAppointmentTimingRequest {
  return { appointmentId: "", doctorId: "", newStartAt: "", newEndAt: "" };
}

export const UpdateAppointmentTimingRequest: MessageFns<UpdateAppointmentTimingRequest> = {
  encode(message: UpdateAppointmentTimingRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.appointmentId !== "") {
      writer.uint32(10).string(message.appointmentId);
    }
    if (message.doctorId !== "") {
      writer.uint32(18).string(message.doctorId);
    }
    if (message.doctorName !== undefined) {
      writer.uint32(26).string(message.doctorName);
    }
    if (message.newStartAt !== "") {
      writer.uint32(34).string(message.newStartAt);
    }
    if (message.newEndAt !== "") {
      writer.uint32(42).string(message.newEndAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateAppointmentTimingRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateAppointmentTimingRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.appointmentId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.doctorId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.doctorName = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.newStartAt = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.newEndAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCheckAppointmentConflictsRequest(): CheckAppointmentConflictsRequest {
  return { doctorId: "", startAt: "", endAt: "" };
}

export const CheckAppointmentConflictsRequest: MessageFns<CheckAppointmentConflictsRequest> = {
  encode(message: CheckAppointmentConflictsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.clinicId !== undefined) {
      writer.uint32(10).string(message.clinicId);
    }
    if (message.doctorId !== "") {
      writer.uint32(18).string(message.doctorId);
    }
    if (message.startAt !== "") {
      writer.uint32(26).string(message.startAt);
    }
    if (message.endAt !== "") {
      writer.uint32(34).string(message.endAt);
    }
    if (message.excludeStatus !== undefined) {
      writer.uint32(42).string(message.excludeStatus);
    }
    if (message.excludeAppointmentId !== undefined) {
      writer.uint32(50).string(message.excludeAppointmentId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CheckAppointmentConflictsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCheckAppointmentConflictsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.clinicId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.doctorId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.startAt = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.endAt = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.excludeStatus = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.excludeAppointmentId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseConflictReply(): ConflictReply {
  return { hasConflict: false };
}

export const ConflictReply: MessageFns<ConflictReply> = {
  encode(message: ConflictReply, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.hasConflict !== false) {
      writer.uint32(8).bool(message.hasConflict);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ConflictReply {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConflictReply();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.hasConflict = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseQueueEntryReply(): QueueEntryReply {
  return {
    id: "",
    clinicId: "",
    appointmentId: "",
    patientId: "",
    patientName: "",
    patientPhone: "",
    doctorId: "",
    doctorName: "",
    appointmentType: "",
    status: "",
    priority: "",
    queueNotes: "",
    arrivedAt: "",
    calledAt: "",
    seatedAt: "",
    completedAt: "",
    updatedAt: "",
  };
}

export const QueueEntryReply: MessageFns<QueueEntryReply> = {
  encode(message: QueueEntryReply, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.clinicId !== "") {
      writer.uint32(18).string(message.clinicId);
    }
    if (message.appointmentId !== "") {
      writer.uint32(26).string(message.appointmentId);
    }
    if (message.patientId !== "") {
      writer.uint32(34).string(message.patientId);
    }
    if (message.patientName !== "") {
      writer.uint32(42).string(message.patientName);
    }
    if (message.patientPhone !== "") {
      writer.uint32(50).string(message.patientPhone);
    }
    if (message.doctorId !== "") {
      writer.uint32(58).string(message.doctorId);
    }
    if (message.doctorName !== "") {
      writer.uint32(66).string(message.doctorName);
    }
    if (message.appointmentType !== "") {
      writer.uint32(74).string(message.appointmentType);
    }
    if (message.status !== "") {
      writer.uint32(82).string(message.status);
    }
    if (message.priority !== "") {
      writer.uint32(90).string(message.priority);
    }
    if (message.queueNotes !== "") {
      writer.uint32(98).string(message.queueNotes);
    }
    if (message.arrivedAt !== "") {
      writer.uint32(106).string(message.arrivedAt);
    }
    if (message.calledAt !== "") {
      writer.uint32(114).string(message.calledAt);
    }
    if (message.seatedAt !== "") {
      writer.uint32(122).string(message.seatedAt);
    }
    if (message.completedAt !== "") {
      writer.uint32(130).string(message.completedAt);
    }
    if (message.updatedAt !== "") {
      writer.uint32(138).string(message.updatedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueueEntryReply {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueueEntryReply();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.clinicId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.appointmentId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.patientId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.patientName = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.patientPhone = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.doctorId = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.doctorName = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.appointmentType = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.priority = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.queueNotes = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.arrivedAt = reader.string();
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.calledAt = reader.string();
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.seatedAt = reader.string();
          continue;
        }
        case 16: {
          if (tag !== 130) {
            break;
          }

          message.completedAt = reader.string();
          continue;
        }
        case 17: {
          if (tag !== 138) {
            break;
          }

          message.updatedAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseQueueEntriesListReply(): QueueEntriesListReply {
  return { queueEntries: [] };
}

export const QueueEntriesListReply: MessageFns<QueueEntriesListReply> = {
  encode(message: QueueEntriesListReply, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.queueEntries) {
      QueueEntryReply.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueueEntriesListReply {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueueEntriesListReply();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.queueEntries.push(QueueEntryReply.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseListQueueEntriesRequest(): ListQueueEntriesRequest {
  return { clinicId: "" };
}

export const ListQueueEntriesRequest: MessageFns<ListQueueEntriesRequest> = {
  encode(message: ListQueueEntriesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.clinicId !== "") {
      writer.uint32(10).string(message.clinicId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListQueueEntriesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListQueueEntriesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.clinicId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetQueueEntryRequest(): GetQueueEntryRequest {
  return { id: "" };
}

export const GetQueueEntryRequest: MessageFns<GetQueueEntryRequest> = {
  encode(message: GetQueueEntryRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetQueueEntryRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetQueueEntryRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCheckInPatientRequest(): CheckInPatientRequest {
  return { clinicId: "", appointmentId: "", patientId: "", patientName: "", doctorId: "", doctorName: "" };
}

export const CheckInPatientRequest: MessageFns<CheckInPatientRequest> = {
  encode(message: CheckInPatientRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.clinicId !== "") {
      writer.uint32(10).string(message.clinicId);
    }
    if (message.appointmentId !== "") {
      writer.uint32(18).string(message.appointmentId);
    }
    if (message.patientId !== "") {
      writer.uint32(26).string(message.patientId);
    }
    if (message.patientName !== "") {
      writer.uint32(34).string(message.patientName);
    }
    if (message.patientPhone !== undefined) {
      writer.uint32(42).string(message.patientPhone);
    }
    if (message.doctorId !== "") {
      writer.uint32(50).string(message.doctorId);
    }
    if (message.doctorName !== "") {
      writer.uint32(58).string(message.doctorName);
    }
    if (message.appointmentType !== undefined) {
      writer.uint32(66).string(message.appointmentType);
    }
    if (message.priority !== undefined) {
      writer.uint32(74).string(message.priority);
    }
    if (message.queueNotes !== undefined) {
      writer.uint32(82).string(message.queueNotes);
    }
    if (message.arrivedAt !== undefined) {
      writer.uint32(90).string(message.arrivedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CheckInPatientRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCheckInPatientRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.clinicId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.appointmentId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.patientId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.patientName = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.patientPhone = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.doctorId = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.doctorName = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.appointmentType = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.priority = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.queueNotes = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.arrivedAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseUpdateQueueStatusRequest(): UpdateQueueStatusRequest {
  return { queueEntryId: "", status: "" };
}

export const UpdateQueueStatusRequest: MessageFns<UpdateQueueStatusRequest> = {
  encode(message: UpdateQueueStatusRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.queueEntryId !== "") {
      writer.uint32(10).string(message.queueEntryId);
    }
    if (message.status !== "") {
      writer.uint32(18).string(message.status);
    }
    if (message.correctionReason !== undefined) {
      writer.uint32(26).string(message.correctionReason);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateQueueStatusRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateQueueStatusRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.queueEntryId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.correctionReason = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseUpdateQueueNotesRequest(): UpdateQueueNotesRequest {
  return { queueEntryId: "" };
}

export const UpdateQueueNotesRequest: MessageFns<UpdateQueueNotesRequest> = {
  encode(message: UpdateQueueNotesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.queueEntryId !== "") {
      writer.uint32(10).string(message.queueEntryId);
    }
    if (message.queueNotes !== undefined) {
      writer.uint32(18).string(message.queueNotes);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateQueueNotesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateQueueNotesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.queueEntryId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.queueNotes = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface AppointmentServiceClient {
  getAppointment(request: GetAppointmentRequest): Observable<AppointmentReply>;

  listAppointments(request: ListAppointmentsRequest): Observable<AppointmentsListReply>;

  createAppointment(request: CreateAppointmentRequest): Observable<AppointmentReply>;

  updateAppointment(request: UpdateAppointmentRequest): Observable<AppointmentReply>;

  updateAppointmentTiming(request: UpdateAppointmentTimingRequest): Observable<AppointmentReply>;

  checkAppointmentConflicts(request: CheckAppointmentConflictsRequest): Observable<ConflictReply>;

  listQueueEntries(request: ListQueueEntriesRequest): Observable<QueueEntriesListReply>;

  getQueueEntry(request: GetQueueEntryRequest): Observable<QueueEntryReply>;

  checkInPatient(request: CheckInPatientRequest): Observable<QueueEntryReply>;

  updateQueueStatus(request: UpdateQueueStatusRequest): Observable<QueueEntryReply>;

  updateQueueNotes(request: UpdateQueueNotesRequest): Observable<QueueEntryReply>;
}

export interface AppointmentServiceController {
  getAppointment(
    request: GetAppointmentRequest,
  ): Promise<AppointmentReply> | Observable<AppointmentReply> | AppointmentReply;

  listAppointments(
    request: ListAppointmentsRequest,
  ): Promise<AppointmentsListReply> | Observable<AppointmentsListReply> | AppointmentsListReply;

  createAppointment(
    request: CreateAppointmentRequest,
  ): Promise<AppointmentReply> | Observable<AppointmentReply> | AppointmentReply;

  updateAppointment(
    request: UpdateAppointmentRequest,
  ): Promise<AppointmentReply> | Observable<AppointmentReply> | AppointmentReply;

  updateAppointmentTiming(
    request: UpdateAppointmentTimingRequest,
  ): Promise<AppointmentReply> | Observable<AppointmentReply> | AppointmentReply;

  checkAppointmentConflicts(
    request: CheckAppointmentConflictsRequest,
  ): Promise<ConflictReply> | Observable<ConflictReply> | ConflictReply;

  listQueueEntries(
    request: ListQueueEntriesRequest,
  ): Promise<QueueEntriesListReply> | Observable<QueueEntriesListReply> | QueueEntriesListReply;

  getQueueEntry(
    request: GetQueueEntryRequest,
  ): Promise<QueueEntryReply> | Observable<QueueEntryReply> | QueueEntryReply;

  checkInPatient(
    request: CheckInPatientRequest,
  ): Promise<QueueEntryReply> | Observable<QueueEntryReply> | QueueEntryReply;

  updateQueueStatus(
    request: UpdateQueueStatusRequest,
  ): Promise<QueueEntryReply> | Observable<QueueEntryReply> | QueueEntryReply;

  updateQueueNotes(
    request: UpdateQueueNotesRequest,
  ): Promise<QueueEntryReply> | Observable<QueueEntryReply> | QueueEntryReply;
}

export function AppointmentServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getAppointment",
      "listAppointments",
      "createAppointment",
      "updateAppointment",
      "updateAppointmentTiming",
      "checkAppointmentConflicts",
      "listQueueEntries",
      "getQueueEntry",
      "checkInPatient",
      "updateQueueStatus",
      "updateQueueNotes",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AppointmentService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AppointmentService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const APPOINTMENT_SERVICE_NAME = "AppointmentService";

export type AppointmentServiceService = typeof AppointmentServiceService;
export const AppointmentServiceService = {
  getAppointment: {
    path: "/appointment.AppointmentService/GetAppointment" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetAppointmentRequest): Buffer =>
      Buffer.from(GetAppointmentRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetAppointmentRequest => GetAppointmentRequest.decode(value),
    responseSerialize: (value: AppointmentReply): Buffer => Buffer.from(AppointmentReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): AppointmentReply => AppointmentReply.decode(value),
  },
  listAppointments: {
    path: "/appointment.AppointmentService/ListAppointments" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ListAppointmentsRequest): Buffer =>
      Buffer.from(ListAppointmentsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ListAppointmentsRequest => ListAppointmentsRequest.decode(value),
    responseSerialize: (value: AppointmentsListReply): Buffer =>
      Buffer.from(AppointmentsListReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): AppointmentsListReply => AppointmentsListReply.decode(value),
  },
  createAppointment: {
    path: "/appointment.AppointmentService/CreateAppointment" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CreateAppointmentRequest): Buffer =>
      Buffer.from(CreateAppointmentRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateAppointmentRequest => CreateAppointmentRequest.decode(value),
    responseSerialize: (value: AppointmentReply): Buffer => Buffer.from(AppointmentReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): AppointmentReply => AppointmentReply.decode(value),
  },
  updateAppointment: {
    path: "/appointment.AppointmentService/UpdateAppointment" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: UpdateAppointmentRequest): Buffer =>
      Buffer.from(UpdateAppointmentRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UpdateAppointmentRequest => UpdateAppointmentRequest.decode(value),
    responseSerialize: (value: AppointmentReply): Buffer => Buffer.from(AppointmentReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): AppointmentReply => AppointmentReply.decode(value),
  },
  updateAppointmentTiming: {
    path: "/appointment.AppointmentService/UpdateAppointmentTiming" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: UpdateAppointmentTimingRequest): Buffer =>
      Buffer.from(UpdateAppointmentTimingRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UpdateAppointmentTimingRequest => UpdateAppointmentTimingRequest.decode(value),
    responseSerialize: (value: AppointmentReply): Buffer => Buffer.from(AppointmentReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): AppointmentReply => AppointmentReply.decode(value),
  },
  checkAppointmentConflicts: {
    path: "/appointment.AppointmentService/CheckAppointmentConflicts" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CheckAppointmentConflictsRequest): Buffer =>
      Buffer.from(CheckAppointmentConflictsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CheckAppointmentConflictsRequest =>
      CheckAppointmentConflictsRequest.decode(value),
    responseSerialize: (value: ConflictReply): Buffer => Buffer.from(ConflictReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): ConflictReply => ConflictReply.decode(value),
  },
  listQueueEntries: {
    path: "/appointment.AppointmentService/ListQueueEntries" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ListQueueEntriesRequest): Buffer =>
      Buffer.from(ListQueueEntriesRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ListQueueEntriesRequest => ListQueueEntriesRequest.decode(value),
    responseSerialize: (value: QueueEntriesListReply): Buffer =>
      Buffer.from(QueueEntriesListReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): QueueEntriesListReply => QueueEntriesListReply.decode(value),
  },
  getQueueEntry: {
    path: "/appointment.AppointmentService/GetQueueEntry" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetQueueEntryRequest): Buffer => Buffer.from(GetQueueEntryRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetQueueEntryRequest => GetQueueEntryRequest.decode(value),
    responseSerialize: (value: QueueEntryReply): Buffer => Buffer.from(QueueEntryReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): QueueEntryReply => QueueEntryReply.decode(value),
  },
  checkInPatient: {
    path: "/appointment.AppointmentService/CheckInPatient" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CheckInPatientRequest): Buffer =>
      Buffer.from(CheckInPatientRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CheckInPatientRequest => CheckInPatientRequest.decode(value),
    responseSerialize: (value: QueueEntryReply): Buffer => Buffer.from(QueueEntryReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): QueueEntryReply => QueueEntryReply.decode(value),
  },
  updateQueueStatus: {
    path: "/appointment.AppointmentService/UpdateQueueStatus" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: UpdateQueueStatusRequest): Buffer =>
      Buffer.from(UpdateQueueStatusRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UpdateQueueStatusRequest => UpdateQueueStatusRequest.decode(value),
    responseSerialize: (value: QueueEntryReply): Buffer => Buffer.from(QueueEntryReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): QueueEntryReply => QueueEntryReply.decode(value),
  },
  updateQueueNotes: {
    path: "/appointment.AppointmentService/UpdateQueueNotes" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: UpdateQueueNotesRequest): Buffer =>
      Buffer.from(UpdateQueueNotesRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UpdateQueueNotesRequest => UpdateQueueNotesRequest.decode(value),
    responseSerialize: (value: QueueEntryReply): Buffer => Buffer.from(QueueEntryReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): QueueEntryReply => QueueEntryReply.decode(value),
  },
} as const;

export interface AppointmentServiceServer extends UntypedServiceImplementation {
  getAppointment: handleUnaryCall<GetAppointmentRequest, AppointmentReply>;
  listAppointments: handleUnaryCall<ListAppointmentsRequest, AppointmentsListReply>;
  createAppointment: handleUnaryCall<CreateAppointmentRequest, AppointmentReply>;
  updateAppointment: handleUnaryCall<UpdateAppointmentRequest, AppointmentReply>;
  updateAppointmentTiming: handleUnaryCall<UpdateAppointmentTimingRequest, AppointmentReply>;
  checkAppointmentConflicts: handleUnaryCall<CheckAppointmentConflictsRequest, ConflictReply>;
  listQueueEntries: handleUnaryCall<ListQueueEntriesRequest, QueueEntriesListReply>;
  getQueueEntry: handleUnaryCall<GetQueueEntryRequest, QueueEntryReply>;
  checkInPatient: handleUnaryCall<CheckInPatientRequest, QueueEntryReply>;
  updateQueueStatus: handleUnaryCall<UpdateQueueStatusRequest, QueueEntryReply>;
  updateQueueNotes: handleUnaryCall<UpdateQueueNotesRequest, QueueEntryReply>;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
