// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.7
//   protoc               v3.19.1
// source: clinic.proto

/* eslint-disable */
import {BinaryReader, BinaryWriter} from "@bufbuild/protobuf/wire";
import type {
  handleUnaryCall,
  UntypedServiceImplementation,
} from "@grpc/grpc-js";
import {GrpcMethod, GrpcStreamMethod} from "@nestjs/microservices";
import {Observable} from "rxjs";

export const protobufPackage = "clinic";

export interface GetClinicRequest {
  id: string;
}

export interface ClinicReply {
  id: string;
  slug: string;
  name: string;
  timezone: string;
  locale: string;
  isActive: boolean;
}

export interface GetStaffMemberRequest {
  userId: string;
  clinicId: string;
}

export interface StaffMemberReply {
  id: string;
  clinicId: string;
  userId: string;
  role: string;
  status: string;
  firstName: string;
  lastName: string;
  phone: string;
  email: string;
  specialization: string;
  avatar: string;
  isActive: boolean;
}

export interface GetWorkingHoursRequest {
  clinicId: string;
}

export interface WorkingHoursEntry {
  id: string;
  clinicId: string;
  dayOfWeek: number;
  openTime: string;
  closeTime: string;
  isClosed: boolean;
}

export interface WorkingHoursListReply {
  entries: WorkingHoursEntry[];
}

export interface CreateClinicRequest {
  slug: string;
  name: string;
  phone?: string | undefined;
  email?: string | undefined;
  address?: string | undefined;
  timezone?: string | undefined;
  locale?: string | undefined;
}

export interface UpsertWorkingHoursRequest {
  clinicId: string;
  entries: WorkingHoursEntryInput[];
}

export interface WorkingHoursEntryInput {
  dayOfWeek: number;
  openTime?: string | undefined;
  closeTime?: string | undefined;
  isClosed: boolean;
}

export interface CreateStaffMemberRequest {
  clinicId: string;
  role: string;
  firstName: string;
  lastName: string;
  phone?: string | undefined;
  email: string;
  specialization?: string | undefined;
  avatar?: string | undefined;
  password: string;
}

export interface ListStaffMembersRequest {
  clinicId: string;
}

export interface StaffMembersListReply {
  staffMembers: StaffMemberReply[];
}

export interface UpdateStaffMemberRequest {
  staffMemberId: string;
  clinicId: string;
  role?: string | undefined;
  status?: string | undefined;
  firstName?: string | undefined;
  lastName?: string | undefined;
  phone?: string | undefined;
  specialization?: string | undefined;
  avatar?: string | undefined;
}

export interface DeleteStaffMemberRequest {
  staffMemberId: string;
  clinicId: string;
}

export interface DeleteStaffMemberReply {
  success: boolean;
}

export const CLINIC_PACKAGE_NAME = "clinic";

function createBaseGetClinicRequest(): GetClinicRequest {
  return {id: ""};
}

export const GetClinicRequest: MessageFns<GetClinicRequest> = {
  encode(
    message: GetClinicRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetClinicRequest {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetClinicRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseClinicReply(): ClinicReply {
  return {
    id: "",
    slug: "",
    name: "",
    timezone: "",
    locale: "",
    isActive: false,
  };
}

export const ClinicReply: MessageFns<ClinicReply> = {
  encode(
    message: ClinicReply,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.slug !== "") {
      writer.uint32(18).string(message.slug);
    }
    if (message.name !== "") {
      writer.uint32(26).string(message.name);
    }
    if (message.timezone !== "") {
      writer.uint32(34).string(message.timezone);
    }
    if (message.locale !== "") {
      writer.uint32(42).string(message.locale);
    }
    if (message.isActive !== false) {
      writer.uint32(48).bool(message.isActive);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ClinicReply {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseClinicReply();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.slug = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.timezone = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.locale = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.isActive = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetStaffMemberRequest(): GetStaffMemberRequest {
  return {userId: "", clinicId: ""};
}

export const GetStaffMemberRequest: MessageFns<GetStaffMemberRequest> = {
  encode(
    message: GetStaffMemberRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.clinicId !== "") {
      writer.uint32(18).string(message.clinicId);
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): GetStaffMemberRequest {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetStaffMemberRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.clinicId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseStaffMemberReply(): StaffMemberReply {
  return {
    id: "",
    clinicId: "",
    userId: "",
    role: "",
    status: "",
    firstName: "",
    lastName: "",
    phone: "",
    email: "",
    specialization: "",
    avatar: "",
    isActive: false,
  };
}

export const StaffMemberReply: MessageFns<StaffMemberReply> = {
  encode(
    message: StaffMemberReply,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.clinicId !== "") {
      writer.uint32(18).string(message.clinicId);
    }
    if (message.userId !== "") {
      writer.uint32(26).string(message.userId);
    }
    if (message.role !== "") {
      writer.uint32(34).string(message.role);
    }
    if (message.status !== "") {
      writer.uint32(42).string(message.status);
    }
    if (message.firstName !== "") {
      writer.uint32(50).string(message.firstName);
    }
    if (message.lastName !== "") {
      writer.uint32(58).string(message.lastName);
    }
    if (message.phone !== "") {
      writer.uint32(66).string(message.phone);
    }
    if (message.email !== "") {
      writer.uint32(74).string(message.email);
    }
    if (message.specialization !== "") {
      writer.uint32(82).string(message.specialization);
    }
    if (message.avatar !== "") {
      writer.uint32(90).string(message.avatar);
    }
    if (message.isActive !== false) {
      writer.uint32(96).bool(message.isActive);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StaffMemberReply {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStaffMemberReply();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.clinicId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.role = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.firstName = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.lastName = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.phone = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.specialization = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.avatar = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.isActive = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetWorkingHoursRequest(): GetWorkingHoursRequest {
  return {clinicId: ""};
}

export const GetWorkingHoursRequest: MessageFns<GetWorkingHoursRequest> = {
  encode(
    message: GetWorkingHoursRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.clinicId !== "") {
      writer.uint32(10).string(message.clinicId);
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): GetWorkingHoursRequest {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetWorkingHoursRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.clinicId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseWorkingHoursEntry(): WorkingHoursEntry {
  return {
    id: "",
    clinicId: "",
    dayOfWeek: 0,
    openTime: "",
    closeTime: "",
    isClosed: false,
  };
}

export const WorkingHoursEntry: MessageFns<WorkingHoursEntry> = {
  encode(
    message: WorkingHoursEntry,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.clinicId !== "") {
      writer.uint32(18).string(message.clinicId);
    }
    if (message.dayOfWeek !== 0) {
      writer.uint32(24).int32(message.dayOfWeek);
    }
    if (message.openTime !== "") {
      writer.uint32(34).string(message.openTime);
    }
    if (message.closeTime !== "") {
      writer.uint32(42).string(message.closeTime);
    }
    if (message.isClosed !== false) {
      writer.uint32(48).bool(message.isClosed);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WorkingHoursEntry {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWorkingHoursEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.clinicId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.dayOfWeek = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.openTime = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.closeTime = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.isClosed = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseWorkingHoursListReply(): WorkingHoursListReply {
  return {entries: []};
}

export const WorkingHoursListReply: MessageFns<WorkingHoursListReply> = {
  encode(
    message: WorkingHoursListReply,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    for (const v of message.entries) {
      WorkingHoursEntry.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): WorkingHoursListReply {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWorkingHoursListReply();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.entries.push(
            WorkingHoursEntry.decode(reader, reader.uint32()),
          );
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCreateClinicRequest(): CreateClinicRequest {
  return {slug: "", name: ""};
}

export const CreateClinicRequest: MessageFns<CreateClinicRequest> = {
  encode(
    message: CreateClinicRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.slug !== "") {
      writer.uint32(10).string(message.slug);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.phone !== undefined) {
      writer.uint32(26).string(message.phone);
    }
    if (message.email !== undefined) {
      writer.uint32(34).string(message.email);
    }
    if (message.address !== undefined) {
      writer.uint32(42).string(message.address);
    }
    if (message.timezone !== undefined) {
      writer.uint32(50).string(message.timezone);
    }
    if (message.locale !== undefined) {
      writer.uint32(58).string(message.locale);
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): CreateClinicRequest {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateClinicRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.slug = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.phone = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.address = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.timezone = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.locale = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseUpsertWorkingHoursRequest(): UpsertWorkingHoursRequest {
  return {clinicId: "", entries: []};
}

export const UpsertWorkingHoursRequest: MessageFns<UpsertWorkingHoursRequest> =
  {
    encode(
      message: UpsertWorkingHoursRequest,
      writer: BinaryWriter = new BinaryWriter(),
    ): BinaryWriter {
      if (message.clinicId !== "") {
        writer.uint32(10).string(message.clinicId);
      }
      for (const v of message.entries) {
        WorkingHoursEntryInput.encode(v!, writer.uint32(18).fork()).join();
      }
      return writer;
    },

    decode(
      input: BinaryReader | Uint8Array,
      length?: number,
    ): UpsertWorkingHoursRequest {
      const reader =
        input instanceof BinaryReader ? input : new BinaryReader(input);
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseUpsertWorkingHoursRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.clinicId = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.entries.push(
              WorkingHoursEntryInput.decode(reader, reader.uint32()),
            );
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    },
  };

function createBaseWorkingHoursEntryInput(): WorkingHoursEntryInput {
  return {dayOfWeek: 0, isClosed: false};
}

export const WorkingHoursEntryInput: MessageFns<WorkingHoursEntryInput> = {
  encode(
    message: WorkingHoursEntryInput,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.dayOfWeek !== 0) {
      writer.uint32(8).int32(message.dayOfWeek);
    }
    if (message.openTime !== undefined) {
      writer.uint32(18).string(message.openTime);
    }
    if (message.closeTime !== undefined) {
      writer.uint32(26).string(message.closeTime);
    }
    if (message.isClosed !== false) {
      writer.uint32(32).bool(message.isClosed);
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): WorkingHoursEntryInput {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWorkingHoursEntryInput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.dayOfWeek = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.openTime = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.closeTime = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.isClosed = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCreateStaffMemberRequest(): CreateStaffMemberRequest {
  return {
    clinicId: "",
    role: "",
    firstName: "",
    lastName: "",
    email: "",
    password: "",
  };
}

export const CreateStaffMemberRequest: MessageFns<CreateStaffMemberRequest> = {
  encode(
    message: CreateStaffMemberRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.clinicId !== "") {
      writer.uint32(10).string(message.clinicId);
    }
    if (message.role !== "") {
      writer.uint32(26).string(message.role);
    }
    if (message.firstName !== "") {
      writer.uint32(34).string(message.firstName);
    }
    if (message.lastName !== "") {
      writer.uint32(42).string(message.lastName);
    }
    if (message.phone !== undefined) {
      writer.uint32(50).string(message.phone);
    }
    if (message.email !== "") {
      writer.uint32(58).string(message.email);
    }
    if (message.specialization !== undefined) {
      writer.uint32(66).string(message.specialization);
    }
    if (message.avatar !== undefined) {
      writer.uint32(74).string(message.avatar);
    }
    if (message.password !== "") {
      writer.uint32(82).string(message.password);
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): CreateStaffMemberRequest {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateStaffMemberRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.clinicId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.role = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.firstName = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.lastName = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.phone = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.specialization = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.avatar = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.password = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseListStaffMembersRequest(): ListStaffMembersRequest {
  return {clinicId: ""};
}

export const ListStaffMembersRequest: MessageFns<ListStaffMembersRequest> = {
  encode(
    message: ListStaffMembersRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.clinicId !== "") {
      writer.uint32(10).string(message.clinicId);
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): ListStaffMembersRequest {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListStaffMembersRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.clinicId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseStaffMembersListReply(): StaffMembersListReply {
  return {staffMembers: []};
}

export const StaffMembersListReply: MessageFns<StaffMembersListReply> = {
  encode(
    message: StaffMembersListReply,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    for (const v of message.staffMembers) {
      StaffMemberReply.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): StaffMembersListReply {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStaffMembersListReply();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.staffMembers.push(
            StaffMemberReply.decode(reader, reader.uint32()),
          );
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface ClinicServiceClient {
  getClinic(request: GetClinicRequest): Observable<ClinicReply>;

  getStaffMember(request: GetStaffMemberRequest): Observable<StaffMemberReply>;

  getWorkingHours(
    request: GetWorkingHoursRequest,
  ): Observable<WorkingHoursListReply>;

  createClinic(request: CreateClinicRequest): Observable<ClinicReply>;

  upsertWorkingHours(
    request: UpsertWorkingHoursRequest,
  ): Observable<WorkingHoursListReply>;

  createStaffMember(
    request: CreateStaffMemberRequest,
  ): Observable<StaffMemberReply>;

  listStaffMembers(
    request: ListStaffMembersRequest,
  ): Observable<StaffMembersListReply>;

  updateStaffMember(
    request: UpdateStaffMemberRequest,
  ): Observable<StaffMemberReply>;

  deleteStaffMember(
    request: DeleteStaffMemberRequest,
  ): Observable<DeleteStaffMemberReply>;
}

export interface ClinicServiceController {
  getClinic(
    request: GetClinicRequest,
  ): Promise<ClinicReply> | Observable<ClinicReply> | ClinicReply;

  getStaffMember(
    request: GetStaffMemberRequest,
  ):
    | Promise<StaffMemberReply>
    | Observable<StaffMemberReply>
    | StaffMemberReply;

  getWorkingHours(
    request: GetWorkingHoursRequest,
  ):
    | Promise<WorkingHoursListReply>
    | Observable<WorkingHoursListReply>
    | WorkingHoursListReply;

  createClinic(
    request: CreateClinicRequest,
  ): Promise<ClinicReply> | Observable<ClinicReply> | ClinicReply;

  upsertWorkingHours(
    request: UpsertWorkingHoursRequest,
  ):
    | Promise<WorkingHoursListReply>
    | Observable<WorkingHoursListReply>
    | WorkingHoursListReply;

  createStaffMember(
    request: CreateStaffMemberRequest,
  ):
    | Promise<StaffMemberReply>
    | Observable<StaffMemberReply>
    | StaffMemberReply;

  listStaffMembers(
    request: ListStaffMembersRequest,
  ):
    | Promise<StaffMembersListReply>
    | Observable<StaffMembersListReply>
    | StaffMembersListReply;

  updateStaffMember(
    request: UpdateStaffMemberRequest,
  ):
    | Promise<StaffMemberReply>
    | Observable<StaffMemberReply>
    | StaffMemberReply;

  deleteStaffMember(
    request: DeleteStaffMemberRequest,
  ):
    | Promise<DeleteStaffMemberReply>
    | Observable<DeleteStaffMemberReply>
    | DeleteStaffMemberReply;
}

export function ClinicServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getClinic",
      "getStaffMember",
      "getWorkingHours",
      "createClinic",
      "upsertWorkingHours",
      "createStaffMember",
      "listStaffMembers",
      "updateStaffMember",
      "deleteStaffMember",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcMethod("ClinicService", method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcStreamMethod("ClinicService", method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const CLINIC_SERVICE_NAME = "ClinicService";

export type ClinicServiceService = typeof ClinicServiceService;
export const ClinicServiceService = {
  getClinic: {
    path: "/clinic.ClinicService/GetClinic" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetClinicRequest): Buffer =>
      Buffer.from(GetClinicRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetClinicRequest =>
      GetClinicRequest.decode(value),
    responseSerialize: (value: ClinicReply): Buffer =>
      Buffer.from(ClinicReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): ClinicReply =>
      ClinicReply.decode(value),
  },
  getStaffMember: {
    path: "/clinic.ClinicService/GetStaffMember" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetStaffMemberRequest): Buffer =>
      Buffer.from(GetStaffMemberRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetStaffMemberRequest =>
      GetStaffMemberRequest.decode(value),
    responseSerialize: (value: StaffMemberReply): Buffer =>
      Buffer.from(StaffMemberReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): StaffMemberReply =>
      StaffMemberReply.decode(value),
  },
  getWorkingHours: {
    path: "/clinic.ClinicService/GetWorkingHours" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetWorkingHoursRequest): Buffer =>
      Buffer.from(GetWorkingHoursRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetWorkingHoursRequest =>
      GetWorkingHoursRequest.decode(value),
    responseSerialize: (value: WorkingHoursListReply): Buffer =>
      Buffer.from(WorkingHoursListReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): WorkingHoursListReply =>
      WorkingHoursListReply.decode(value),
  },
  createClinic: {
    path: "/clinic.ClinicService/CreateClinic" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CreateClinicRequest): Buffer =>
      Buffer.from(CreateClinicRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateClinicRequest =>
      CreateClinicRequest.decode(value),
    responseSerialize: (value: ClinicReply): Buffer =>
      Buffer.from(ClinicReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): ClinicReply =>
      ClinicReply.decode(value),
  },
  upsertWorkingHours: {
    path: "/clinic.ClinicService/UpsertWorkingHours" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: UpsertWorkingHoursRequest): Buffer =>
      Buffer.from(UpsertWorkingHoursRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UpsertWorkingHoursRequest =>
      UpsertWorkingHoursRequest.decode(value),
    responseSerialize: (value: WorkingHoursListReply): Buffer =>
      Buffer.from(WorkingHoursListReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): WorkingHoursListReply =>
      WorkingHoursListReply.decode(value),
  },
  createStaffMember: {
    path: "/clinic.ClinicService/CreateStaffMember" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CreateStaffMemberRequest): Buffer =>
      Buffer.from(CreateStaffMemberRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateStaffMemberRequest =>
      CreateStaffMemberRequest.decode(value),
    responseSerialize: (value: StaffMemberReply): Buffer =>
      Buffer.from(StaffMemberReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): StaffMemberReply =>
      StaffMemberReply.decode(value),
  },
  listStaffMembers: {
    path: "/clinic.ClinicService/ListStaffMembers" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ListStaffMembersRequest): Buffer =>
      Buffer.from(ListStaffMembersRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ListStaffMembersRequest =>
      ListStaffMembersRequest.decode(value),
    responseSerialize: (value: StaffMembersListReply): Buffer =>
      Buffer.from(StaffMembersListReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): StaffMembersListReply =>
      StaffMembersListReply.decode(value),
  },
} as const;

export interface ClinicServiceServer extends UntypedServiceImplementation {
  getClinic: handleUnaryCall<GetClinicRequest, ClinicReply>;
  getStaffMember: handleUnaryCall<GetStaffMemberRequest, StaffMemberReply>;
  getWorkingHours: handleUnaryCall<
    GetWorkingHoursRequest,
    WorkingHoursListReply
  >;
  createClinic: handleUnaryCall<CreateClinicRequest, ClinicReply>;
  upsertWorkingHours: handleUnaryCall<
    UpsertWorkingHoursRequest,
    WorkingHoursListReply
  >;
  createStaffMember: handleUnaryCall<
    CreateStaffMemberRequest,
    StaffMemberReply
  >;
  listStaffMembers: handleUnaryCall<
    ListStaffMembersRequest,
    StaffMembersListReply
  >;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
