// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.7
//   protoc               v3.19.1
// source: treatment.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { handleUnaryCall, UntypedServiceImplementation } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "treatment";

export interface VisitReply {
  id: string;
  clinicId: string;
  appointmentId: string;
  patientId: string;
  patientName: string;
  doctorId: string;
  doctorName: string;
  assistantId: string;
  assistantName: string;
  status: string;
  totalAmount: number;
  confirmedAt: string;
  confirmedBy: string;
  voidedAt: string;
  voidReason: string;
  createdAt: string;
  updatedAt: string;
  treatmentActs: TreatmentActReply[];
}

export interface NullableVisitReply {
  visit?: VisitReply | undefined;
}

export interface VisitsListReply {
  visits: VisitReply[];
  total: number;
}

export interface GetVisitRequest {
  id: string;
}

export interface GetVisitByAppointmentRequest {
  appointmentId: string;
}

export interface ListOpenVisitsRequest {
  clinicId: string;
  doctorId?: string | undefined;
}

export interface OpenVisitRequest {
  clinicId: string;
  appointmentId: string;
  patientId: string;
  patientName: string;
  doctorId: string;
  doctorName: string;
}

export interface AssignAssistantRequest {
  visitId: string;
  assistantId: string;
  assistantName: string;
}

export interface ConfirmVisitRequest {
  visitId: string;
  confirmedBy: string;
}

export interface CloseVisitRequest {
  visitId: string;
}

export interface VoidVisitRequest {
  visitId: string;
  reason: string;
}

export interface ActCatalogReply {
  id: string;
  clinicId: string;
  code: string;
  nameAr: string;
  nameFr: string;
  nameEn: string;
  defaultPrice: number;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface ActCatalogListReply {
  items: ActCatalogReply[];
  total: number;
}

export interface ListActCatalogRequest {
  clinicId: string;
  locale?: string | undefined;
  page?: number | undefined;
  limit?: number | undefined;
}

export interface GetActCatalogRequest {
  id: string;
}

export interface CreateActCatalogRequest {
  clinicId: string;
  code: string;
  nameAr: string;
  nameFr: string;
  nameEn: string;
  defaultPrice: number;
  isActive?: boolean | undefined;
}

export interface UpdateActCatalogRequest {
  id: string;
  code?: string | undefined;
  nameAr?: string | undefined;
  nameFr?: string | undefined;
  nameEn?: string | undefined;
  defaultPrice?: number | undefined;
  isActive?: boolean | undefined;
}

export interface DeleteActCatalogRequest {
  id: string;
}

export interface TreatmentActReply {
  id: string;
  clinicId: string;
  visitId: string;
  actCatalogId: string;
  toothFdi: string;
  quantity: number;
  unitPrice: number;
  surface: string;
  toothPart: string;
  dentition: string;
  status: string;
  notes: string;
  enteredBy: string;
  createdAt: string;
  updatedAt: string;
}

export interface TreatmentActListReply {
  treatmentActs: TreatmentActReply[];
  total: number;
}

export interface ListTreatmentActsRequest {
  visitId: string;
}

export interface GetTreatmentActRequest {
  id: string;
}

export interface AddTreatmentActRequest {
  clinicId: string;
  visitId: string;
  actCatalogId: string;
  toothFdi?: string | undefined;
  quantity?: number | undefined;
  surface?: string | undefined;
  toothPart?: string | undefined;
  dentition?: string | undefined;
  status?: string | undefined;
  notes?: string | undefined;
  enteredBy: string;
}

export interface UpdateTreatmentActRequest {
  id: string;
  toothFdi?: string | undefined;
  quantity?: number | undefined;
  surface?: string | undefined;
  toothPart?: string | undefined;
  dentition?: string | undefined;
  status?: string | undefined;
  notes?: string | undefined;
}

export interface RemoveTreatmentActRequest {
  id: string;
}

export interface CalculateVisitTotalRequest {
  visitId: string;
}

export interface VisitTotalReply {
  totalAmount: number;
}

export interface EmptyReply {
}

export const TREATMENT_PACKAGE_NAME = "treatment";

function createBaseVisitReply(): VisitReply {
  return {
    id: "",
    clinicId: "",
    appointmentId: "",
    patientId: "",
    patientName: "",
    doctorId: "",
    doctorName: "",
    assistantId: "",
    assistantName: "",
    status: "",
    totalAmount: 0,
    confirmedAt: "",
    confirmedBy: "",
    voidedAt: "",
    voidReason: "",
    createdAt: "",
    updatedAt: "",
    treatmentActs: [],
  };
}

export const VisitReply: MessageFns<VisitReply> = {
  encode(message: VisitReply, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.clinicId !== "") {
      writer.uint32(18).string(message.clinicId);
    }
    if (message.appointmentId !== "") {
      writer.uint32(26).string(message.appointmentId);
    }
    if (message.patientId !== "") {
      writer.uint32(34).string(message.patientId);
    }
    if (message.patientName !== "") {
      writer.uint32(42).string(message.patientName);
    }
    if (message.doctorId !== "") {
      writer.uint32(50).string(message.doctorId);
    }
    if (message.doctorName !== "") {
      writer.uint32(58).string(message.doctorName);
    }
    if (message.assistantId !== "") {
      writer.uint32(66).string(message.assistantId);
    }
    if (message.assistantName !== "") {
      writer.uint32(74).string(message.assistantName);
    }
    if (message.status !== "") {
      writer.uint32(82).string(message.status);
    }
    if (message.totalAmount !== 0) {
      writer.uint32(89).double(message.totalAmount);
    }
    if (message.confirmedAt !== "") {
      writer.uint32(98).string(message.confirmedAt);
    }
    if (message.confirmedBy !== "") {
      writer.uint32(106).string(message.confirmedBy);
    }
    if (message.voidedAt !== "") {
      writer.uint32(114).string(message.voidedAt);
    }
    if (message.voidReason !== "") {
      writer.uint32(122).string(message.voidReason);
    }
    if (message.createdAt !== "") {
      writer.uint32(130).string(message.createdAt);
    }
    if (message.updatedAt !== "") {
      writer.uint32(138).string(message.updatedAt);
    }
    for (const v of message.treatmentActs) {
      TreatmentActReply.encode(v!, writer.uint32(146).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VisitReply {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVisitReply();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.clinicId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.appointmentId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.patientId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.patientName = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.doctorId = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.doctorName = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.assistantId = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.assistantName = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 89) {
            break;
          }

          message.totalAmount = reader.double();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.confirmedAt = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.confirmedBy = reader.string();
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.voidedAt = reader.string();
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.voidReason = reader.string();
          continue;
        }
        case 16: {
          if (tag !== 130) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
        case 17: {
          if (tag !== 138) {
            break;
          }

          message.updatedAt = reader.string();
          continue;
        }
        case 18: {
          if (tag !== 146) {
            break;
          }

          message.treatmentActs.push(TreatmentActReply.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseNullableVisitReply(): NullableVisitReply {
  return {};
}

export const NullableVisitReply: MessageFns<NullableVisitReply> = {
  encode(message: NullableVisitReply, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.visit !== undefined) {
      VisitReply.encode(message.visit, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NullableVisitReply {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNullableVisitReply();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.visit = VisitReply.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseVisitsListReply(): VisitsListReply {
  return { visits: [], total: 0 };
}

export const VisitsListReply: MessageFns<VisitsListReply> = {
  encode(message: VisitsListReply, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.visits) {
      VisitReply.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.total !== 0) {
      writer.uint32(16).int32(message.total);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VisitsListReply {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVisitsListReply();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.visits.push(VisitReply.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.total = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetVisitRequest(): GetVisitRequest {
  return { id: "" };
}

export const GetVisitRequest: MessageFns<GetVisitRequest> = {
  encode(message: GetVisitRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetVisitRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetVisitRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetVisitByAppointmentRequest(): GetVisitByAppointmentRequest {
  return { appointmentId: "" };
}

export const GetVisitByAppointmentRequest: MessageFns<GetVisitByAppointmentRequest> = {
  encode(message: GetVisitByAppointmentRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.appointmentId !== "") {
      writer.uint32(10).string(message.appointmentId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetVisitByAppointmentRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetVisitByAppointmentRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.appointmentId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseListOpenVisitsRequest(): ListOpenVisitsRequest {
  return { clinicId: "" };
}

export const ListOpenVisitsRequest: MessageFns<ListOpenVisitsRequest> = {
  encode(message: ListOpenVisitsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.clinicId !== "") {
      writer.uint32(10).string(message.clinicId);
    }
    if (message.doctorId !== undefined) {
      writer.uint32(18).string(message.doctorId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListOpenVisitsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListOpenVisitsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.clinicId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.doctorId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseOpenVisitRequest(): OpenVisitRequest {
  return { clinicId: "", appointmentId: "", patientId: "", patientName: "", doctorId: "", doctorName: "" };
}

export const OpenVisitRequest: MessageFns<OpenVisitRequest> = {
  encode(message: OpenVisitRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.clinicId !== "") {
      writer.uint32(10).string(message.clinicId);
    }
    if (message.appointmentId !== "") {
      writer.uint32(18).string(message.appointmentId);
    }
    if (message.patientId !== "") {
      writer.uint32(26).string(message.patientId);
    }
    if (message.patientName !== "") {
      writer.uint32(34).string(message.patientName);
    }
    if (message.doctorId !== "") {
      writer.uint32(42).string(message.doctorId);
    }
    if (message.doctorName !== "") {
      writer.uint32(50).string(message.doctorName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OpenVisitRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOpenVisitRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.clinicId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.appointmentId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.patientId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.patientName = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.doctorId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.doctorName = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseAssignAssistantRequest(): AssignAssistantRequest {
  return { visitId: "", assistantId: "", assistantName: "" };
}

export const AssignAssistantRequest: MessageFns<AssignAssistantRequest> = {
  encode(message: AssignAssistantRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.visitId !== "") {
      writer.uint32(10).string(message.visitId);
    }
    if (message.assistantId !== "") {
      writer.uint32(18).string(message.assistantId);
    }
    if (message.assistantName !== "") {
      writer.uint32(26).string(message.assistantName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AssignAssistantRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAssignAssistantRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.visitId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.assistantId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.assistantName = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseConfirmVisitRequest(): ConfirmVisitRequest {
  return { visitId: "", confirmedBy: "" };
}

export const ConfirmVisitRequest: MessageFns<ConfirmVisitRequest> = {
  encode(message: ConfirmVisitRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.visitId !== "") {
      writer.uint32(10).string(message.visitId);
    }
    if (message.confirmedBy !== "") {
      writer.uint32(18).string(message.confirmedBy);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ConfirmVisitRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConfirmVisitRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.visitId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.confirmedBy = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCloseVisitRequest(): CloseVisitRequest {
  return { visitId: "" };
}

export const CloseVisitRequest: MessageFns<CloseVisitRequest> = {
  encode(message: CloseVisitRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.visitId !== "") {
      writer.uint32(10).string(message.visitId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CloseVisitRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCloseVisitRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.visitId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseVoidVisitRequest(): VoidVisitRequest {
  return { visitId: "", reason: "" };
}

export const VoidVisitRequest: MessageFns<VoidVisitRequest> = {
  encode(message: VoidVisitRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.visitId !== "") {
      writer.uint32(10).string(message.visitId);
    }
    if (message.reason !== "") {
      writer.uint32(18).string(message.reason);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VoidVisitRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVoidVisitRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.visitId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.reason = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseActCatalogReply(): ActCatalogReply {
  return {
    id: "",
    clinicId: "",
    code: "",
    nameAr: "",
    nameFr: "",
    nameEn: "",
    defaultPrice: 0,
    isActive: false,
    createdAt: "",
    updatedAt: "",
  };
}

export const ActCatalogReply: MessageFns<ActCatalogReply> = {
  encode(message: ActCatalogReply, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.clinicId !== "") {
      writer.uint32(18).string(message.clinicId);
    }
    if (message.code !== "") {
      writer.uint32(26).string(message.code);
    }
    if (message.nameAr !== "") {
      writer.uint32(34).string(message.nameAr);
    }
    if (message.nameFr !== "") {
      writer.uint32(42).string(message.nameFr);
    }
    if (message.nameEn !== "") {
      writer.uint32(50).string(message.nameEn);
    }
    if (message.defaultPrice !== 0) {
      writer.uint32(57).double(message.defaultPrice);
    }
    if (message.isActive !== false) {
      writer.uint32(64).bool(message.isActive);
    }
    if (message.createdAt !== "") {
      writer.uint32(74).string(message.createdAt);
    }
    if (message.updatedAt !== "") {
      writer.uint32(82).string(message.updatedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ActCatalogReply {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseActCatalogReply();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.clinicId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.code = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.nameAr = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.nameFr = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.nameEn = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 57) {
            break;
          }

          message.defaultPrice = reader.double();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.isActive = reader.bool();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.updatedAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseActCatalogListReply(): ActCatalogListReply {
  return { items: [], total: 0 };
}

export const ActCatalogListReply: MessageFns<ActCatalogListReply> = {
  encode(message: ActCatalogListReply, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.items) {
      ActCatalogReply.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.total !== 0) {
      writer.uint32(16).int32(message.total);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ActCatalogListReply {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseActCatalogListReply();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.items.push(ActCatalogReply.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.total = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseListActCatalogRequest(): ListActCatalogRequest {
  return { clinicId: "" };
}

export const ListActCatalogRequest: MessageFns<ListActCatalogRequest> = {
  encode(message: ListActCatalogRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.clinicId !== "") {
      writer.uint32(10).string(message.clinicId);
    }
    if (message.locale !== undefined) {
      writer.uint32(18).string(message.locale);
    }
    if (message.page !== undefined) {
      writer.uint32(24).int32(message.page);
    }
    if (message.limit !== undefined) {
      writer.uint32(32).int32(message.limit);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListActCatalogRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListActCatalogRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.clinicId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.locale = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.page = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetActCatalogRequest(): GetActCatalogRequest {
  return { id: "" };
}

export const GetActCatalogRequest: MessageFns<GetActCatalogRequest> = {
  encode(message: GetActCatalogRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetActCatalogRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetActCatalogRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCreateActCatalogRequest(): CreateActCatalogRequest {
  return { clinicId: "", code: "", nameAr: "", nameFr: "", nameEn: "", defaultPrice: 0 };
}

export const CreateActCatalogRequest: MessageFns<CreateActCatalogRequest> = {
  encode(message: CreateActCatalogRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.clinicId !== "") {
      writer.uint32(10).string(message.clinicId);
    }
    if (message.code !== "") {
      writer.uint32(18).string(message.code);
    }
    if (message.nameAr !== "") {
      writer.uint32(26).string(message.nameAr);
    }
    if (message.nameFr !== "") {
      writer.uint32(34).string(message.nameFr);
    }
    if (message.nameEn !== "") {
      writer.uint32(42).string(message.nameEn);
    }
    if (message.defaultPrice !== 0) {
      writer.uint32(49).double(message.defaultPrice);
    }
    if (message.isActive !== undefined) {
      writer.uint32(56).bool(message.isActive);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateActCatalogRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateActCatalogRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.clinicId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.code = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.nameAr = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.nameFr = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.nameEn = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 49) {
            break;
          }

          message.defaultPrice = reader.double();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.isActive = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseUpdateActCatalogRequest(): UpdateActCatalogRequest {
  return { id: "" };
}

export const UpdateActCatalogRequest: MessageFns<UpdateActCatalogRequest> = {
  encode(message: UpdateActCatalogRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.code !== undefined) {
      writer.uint32(18).string(message.code);
    }
    if (message.nameAr !== undefined) {
      writer.uint32(26).string(message.nameAr);
    }
    if (message.nameFr !== undefined) {
      writer.uint32(34).string(message.nameFr);
    }
    if (message.nameEn !== undefined) {
      writer.uint32(42).string(message.nameEn);
    }
    if (message.defaultPrice !== undefined) {
      writer.uint32(49).double(message.defaultPrice);
    }
    if (message.isActive !== undefined) {
      writer.uint32(56).bool(message.isActive);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateActCatalogRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateActCatalogRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.code = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.nameAr = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.nameFr = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.nameEn = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 49) {
            break;
          }

          message.defaultPrice = reader.double();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.isActive = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseDeleteActCatalogRequest(): DeleteActCatalogRequest {
  return { id: "" };
}

export const DeleteActCatalogRequest: MessageFns<DeleteActCatalogRequest> = {
  encode(message: DeleteActCatalogRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteActCatalogRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteActCatalogRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseTreatmentActReply(): TreatmentActReply {
  return {
    id: "",
    clinicId: "",
    visitId: "",
    actCatalogId: "",
    toothFdi: "",
    quantity: 0,
    unitPrice: 0,
    surface: "",
    toothPart: "",
    dentition: "",
    status: "",
    notes: "",
    enteredBy: "",
    createdAt: "",
    updatedAt: "",
  };
}

export const TreatmentActReply: MessageFns<TreatmentActReply> = {
  encode(message: TreatmentActReply, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.clinicId !== "") {
      writer.uint32(18).string(message.clinicId);
    }
    if (message.visitId !== "") {
      writer.uint32(26).string(message.visitId);
    }
    if (message.actCatalogId !== "") {
      writer.uint32(34).string(message.actCatalogId);
    }
    if (message.toothFdi !== "") {
      writer.uint32(42).string(message.toothFdi);
    }
    if (message.quantity !== 0) {
      writer.uint32(48).int32(message.quantity);
    }
    if (message.unitPrice !== 0) {
      writer.uint32(57).double(message.unitPrice);
    }
    if (message.surface !== "") {
      writer.uint32(66).string(message.surface);
    }
    if (message.toothPart !== "") {
      writer.uint32(74).string(message.toothPart);
    }
    if (message.dentition !== "") {
      writer.uint32(82).string(message.dentition);
    }
    if (message.status !== "") {
      writer.uint32(90).string(message.status);
    }
    if (message.notes !== "") {
      writer.uint32(98).string(message.notes);
    }
    if (message.enteredBy !== "") {
      writer.uint32(106).string(message.enteredBy);
    }
    if (message.createdAt !== "") {
      writer.uint32(114).string(message.createdAt);
    }
    if (message.updatedAt !== "") {
      writer.uint32(122).string(message.updatedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TreatmentActReply {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTreatmentActReply();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.clinicId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.visitId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.actCatalogId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.toothFdi = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.quantity = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 57) {
            break;
          }

          message.unitPrice = reader.double();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.surface = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.toothPart = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.dentition = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.notes = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.enteredBy = reader.string();
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.updatedAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseTreatmentActListReply(): TreatmentActListReply {
  return { treatmentActs: [], total: 0 };
}

export const TreatmentActListReply: MessageFns<TreatmentActListReply> = {
  encode(message: TreatmentActListReply, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.treatmentActs) {
      TreatmentActReply.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.total !== 0) {
      writer.uint32(16).int32(message.total);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TreatmentActListReply {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTreatmentActListReply();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.treatmentActs.push(TreatmentActReply.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.total = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseListTreatmentActsRequest(): ListTreatmentActsRequest {
  return { visitId: "" };
}

export const ListTreatmentActsRequest: MessageFns<ListTreatmentActsRequest> = {
  encode(message: ListTreatmentActsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.visitId !== "") {
      writer.uint32(10).string(message.visitId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListTreatmentActsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListTreatmentActsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.visitId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetTreatmentActRequest(): GetTreatmentActRequest {
  return { id: "" };
}

export const GetTreatmentActRequest: MessageFns<GetTreatmentActRequest> = {
  encode(message: GetTreatmentActRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTreatmentActRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTreatmentActRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseAddTreatmentActRequest(): AddTreatmentActRequest {
  return { clinicId: "", visitId: "", actCatalogId: "", enteredBy: "" };
}

export const AddTreatmentActRequest: MessageFns<AddTreatmentActRequest> = {
  encode(message: AddTreatmentActRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.clinicId !== "") {
      writer.uint32(10).string(message.clinicId);
    }
    if (message.visitId !== "") {
      writer.uint32(18).string(message.visitId);
    }
    if (message.actCatalogId !== "") {
      writer.uint32(26).string(message.actCatalogId);
    }
    if (message.toothFdi !== undefined) {
      writer.uint32(34).string(message.toothFdi);
    }
    if (message.quantity !== undefined) {
      writer.uint32(40).int32(message.quantity);
    }
    if (message.surface !== undefined) {
      writer.uint32(50).string(message.surface);
    }
    if (message.toothPart !== undefined) {
      writer.uint32(58).string(message.toothPart);
    }
    if (message.dentition !== undefined) {
      writer.uint32(66).string(message.dentition);
    }
    if (message.status !== undefined) {
      writer.uint32(74).string(message.status);
    }
    if (message.notes !== undefined) {
      writer.uint32(82).string(message.notes);
    }
    if (message.enteredBy !== "") {
      writer.uint32(90).string(message.enteredBy);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddTreatmentActRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddTreatmentActRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.clinicId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.visitId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.actCatalogId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.toothFdi = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.quantity = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.surface = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.toothPart = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.dentition = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.notes = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.enteredBy = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseUpdateTreatmentActRequest(): UpdateTreatmentActRequest {
  return { id: "" };
}

export const UpdateTreatmentActRequest: MessageFns<UpdateTreatmentActRequest> = {
  encode(message: UpdateTreatmentActRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.toothFdi !== undefined) {
      writer.uint32(18).string(message.toothFdi);
    }
    if (message.quantity !== undefined) {
      writer.uint32(24).int32(message.quantity);
    }
    if (message.surface !== undefined) {
      writer.uint32(34).string(message.surface);
    }
    if (message.toothPart !== undefined) {
      writer.uint32(42).string(message.toothPart);
    }
    if (message.dentition !== undefined) {
      writer.uint32(50).string(message.dentition);
    }
    if (message.status !== undefined) {
      writer.uint32(58).string(message.status);
    }
    if (message.notes !== undefined) {
      writer.uint32(66).string(message.notes);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateTreatmentActRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateTreatmentActRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.toothFdi = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.quantity = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.surface = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.toothPart = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.dentition = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.notes = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseRemoveTreatmentActRequest(): RemoveTreatmentActRequest {
  return { id: "" };
}

export const RemoveTreatmentActRequest: MessageFns<RemoveTreatmentActRequest> = {
  encode(message: RemoveTreatmentActRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RemoveTreatmentActRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRemoveTreatmentActRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCalculateVisitTotalRequest(): CalculateVisitTotalRequest {
  return { visitId: "" };
}

export const CalculateVisitTotalRequest: MessageFns<CalculateVisitTotalRequest> = {
  encode(message: CalculateVisitTotalRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.visitId !== "") {
      writer.uint32(10).string(message.visitId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CalculateVisitTotalRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCalculateVisitTotalRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.visitId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseVisitTotalReply(): VisitTotalReply {
  return { totalAmount: 0 };
}

export const VisitTotalReply: MessageFns<VisitTotalReply> = {
  encode(message: VisitTotalReply, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.totalAmount !== 0) {
      writer.uint32(9).double(message.totalAmount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VisitTotalReply {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVisitTotalReply();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.totalAmount = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseEmptyReply(): EmptyReply {
  return {};
}

export const EmptyReply: MessageFns<EmptyReply> = {
  encode(_: EmptyReply, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EmptyReply {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmptyReply();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface TreatmentServiceClient {
  getVisit(request: GetVisitRequest): Observable<VisitReply>;

  getVisitByAppointment(request: GetVisitByAppointmentRequest): Observable<NullableVisitReply>;

  listOpenVisits(request: ListOpenVisitsRequest): Observable<VisitsListReply>;

  openVisit(request: OpenVisitRequest): Observable<VisitReply>;

  assignAssistant(request: AssignAssistantRequest): Observable<VisitReply>;

  confirmVisit(request: ConfirmVisitRequest): Observable<VisitReply>;

  closeVisit(request: CloseVisitRequest): Observable<VisitReply>;

  voidVisit(request: VoidVisitRequest): Observable<VisitReply>;

  listActCatalog(request: ListActCatalogRequest): Observable<ActCatalogListReply>;

  getActCatalog(request: GetActCatalogRequest): Observable<ActCatalogReply>;

  createActCatalog(request: CreateActCatalogRequest): Observable<ActCatalogReply>;

  updateActCatalog(request: UpdateActCatalogRequest): Observable<ActCatalogReply>;

  deleteActCatalog(request: DeleteActCatalogRequest): Observable<EmptyReply>;

  listTreatmentActs(request: ListTreatmentActsRequest): Observable<TreatmentActListReply>;

  getTreatmentAct(request: GetTreatmentActRequest): Observable<TreatmentActReply>;

  addTreatmentAct(request: AddTreatmentActRequest): Observable<TreatmentActReply>;

  updateTreatmentAct(request: UpdateTreatmentActRequest): Observable<TreatmentActReply>;

  removeTreatmentAct(request: RemoveTreatmentActRequest): Observable<EmptyReply>;

  calculateVisitTotal(request: CalculateVisitTotalRequest): Observable<VisitTotalReply>;
}

export interface TreatmentServiceController {
  getVisit(request: GetVisitRequest): Promise<VisitReply> | Observable<VisitReply> | VisitReply;

  getVisitByAppointment(
    request: GetVisitByAppointmentRequest,
  ): Promise<NullableVisitReply> | Observable<NullableVisitReply> | NullableVisitReply;

  listOpenVisits(
    request: ListOpenVisitsRequest,
  ): Promise<VisitsListReply> | Observable<VisitsListReply> | VisitsListReply;

  openVisit(request: OpenVisitRequest): Promise<VisitReply> | Observable<VisitReply> | VisitReply;

  assignAssistant(request: AssignAssistantRequest): Promise<VisitReply> | Observable<VisitReply> | VisitReply;

  confirmVisit(request: ConfirmVisitRequest): Promise<VisitReply> | Observable<VisitReply> | VisitReply;

  closeVisit(request: CloseVisitRequest): Promise<VisitReply> | Observable<VisitReply> | VisitReply;

  voidVisit(request: VoidVisitRequest): Promise<VisitReply> | Observable<VisitReply> | VisitReply;

  listActCatalog(
    request: ListActCatalogRequest,
  ): Promise<ActCatalogListReply> | Observable<ActCatalogListReply> | ActCatalogListReply;

  getActCatalog(
    request: GetActCatalogRequest,
  ): Promise<ActCatalogReply> | Observable<ActCatalogReply> | ActCatalogReply;

  createActCatalog(
    request: CreateActCatalogRequest,
  ): Promise<ActCatalogReply> | Observable<ActCatalogReply> | ActCatalogReply;

  updateActCatalog(
    request: UpdateActCatalogRequest,
  ): Promise<ActCatalogReply> | Observable<ActCatalogReply> | ActCatalogReply;

  deleteActCatalog(request: DeleteActCatalogRequest): Promise<EmptyReply> | Observable<EmptyReply> | EmptyReply;

  listTreatmentActs(
    request: ListTreatmentActsRequest,
  ): Promise<TreatmentActListReply> | Observable<TreatmentActListReply> | TreatmentActListReply;

  getTreatmentAct(
    request: GetTreatmentActRequest,
  ): Promise<TreatmentActReply> | Observable<TreatmentActReply> | TreatmentActReply;

  addTreatmentAct(
    request: AddTreatmentActRequest,
  ): Promise<TreatmentActReply> | Observable<TreatmentActReply> | TreatmentActReply;

  updateTreatmentAct(
    request: UpdateTreatmentActRequest,
  ): Promise<TreatmentActReply> | Observable<TreatmentActReply> | TreatmentActReply;

  removeTreatmentAct(request: RemoveTreatmentActRequest): Promise<EmptyReply> | Observable<EmptyReply> | EmptyReply;

  calculateVisitTotal(
    request: CalculateVisitTotalRequest,
  ): Promise<VisitTotalReply> | Observable<VisitTotalReply> | VisitTotalReply;
}

export function TreatmentServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getVisit",
      "getVisitByAppointment",
      "listOpenVisits",
      "openVisit",
      "assignAssistant",
      "confirmVisit",
      "closeVisit",
      "voidVisit",
      "listActCatalog",
      "getActCatalog",
      "createActCatalog",
      "updateActCatalog",
      "deleteActCatalog",
      "listTreatmentActs",
      "getTreatmentAct",
      "addTreatmentAct",
      "updateTreatmentAct",
      "removeTreatmentAct",
      "calculateVisitTotal",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("TreatmentService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("TreatmentService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const TREATMENT_SERVICE_NAME = "TreatmentService";

export type TreatmentServiceService = typeof TreatmentServiceService;
export const TreatmentServiceService = {
  getVisit: {
    path: "/treatment.TreatmentService/GetVisit" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetVisitRequest): Buffer => Buffer.from(GetVisitRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetVisitRequest => GetVisitRequest.decode(value),
    responseSerialize: (value: VisitReply): Buffer => Buffer.from(VisitReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): VisitReply => VisitReply.decode(value),
  },
  getVisitByAppointment: {
    path: "/treatment.TreatmentService/GetVisitByAppointment" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetVisitByAppointmentRequest): Buffer =>
      Buffer.from(GetVisitByAppointmentRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetVisitByAppointmentRequest => GetVisitByAppointmentRequest.decode(value),
    responseSerialize: (value: NullableVisitReply): Buffer => Buffer.from(NullableVisitReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): NullableVisitReply => NullableVisitReply.decode(value),
  },
  listOpenVisits: {
    path: "/treatment.TreatmentService/ListOpenVisits" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ListOpenVisitsRequest): Buffer =>
      Buffer.from(ListOpenVisitsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ListOpenVisitsRequest => ListOpenVisitsRequest.decode(value),
    responseSerialize: (value: VisitsListReply): Buffer => Buffer.from(VisitsListReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): VisitsListReply => VisitsListReply.decode(value),
  },
  openVisit: {
    path: "/treatment.TreatmentService/OpenVisit" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: OpenVisitRequest): Buffer => Buffer.from(OpenVisitRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): OpenVisitRequest => OpenVisitRequest.decode(value),
    responseSerialize: (value: VisitReply): Buffer => Buffer.from(VisitReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): VisitReply => VisitReply.decode(value),
  },
  assignAssistant: {
    path: "/treatment.TreatmentService/AssignAssistant" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: AssignAssistantRequest): Buffer =>
      Buffer.from(AssignAssistantRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): AssignAssistantRequest => AssignAssistantRequest.decode(value),
    responseSerialize: (value: VisitReply): Buffer => Buffer.from(VisitReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): VisitReply => VisitReply.decode(value),
  },
  confirmVisit: {
    path: "/treatment.TreatmentService/ConfirmVisit" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ConfirmVisitRequest): Buffer => Buffer.from(ConfirmVisitRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ConfirmVisitRequest => ConfirmVisitRequest.decode(value),
    responseSerialize: (value: VisitReply): Buffer => Buffer.from(VisitReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): VisitReply => VisitReply.decode(value),
  },
  closeVisit: {
    path: "/treatment.TreatmentService/CloseVisit" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CloseVisitRequest): Buffer => Buffer.from(CloseVisitRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CloseVisitRequest => CloseVisitRequest.decode(value),
    responseSerialize: (value: VisitReply): Buffer => Buffer.from(VisitReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): VisitReply => VisitReply.decode(value),
  },
  voidVisit: {
    path: "/treatment.TreatmentService/VoidVisit" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: VoidVisitRequest): Buffer => Buffer.from(VoidVisitRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): VoidVisitRequest => VoidVisitRequest.decode(value),
    responseSerialize: (value: VisitReply): Buffer => Buffer.from(VisitReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): VisitReply => VisitReply.decode(value),
  },
  listActCatalog: {
    path: "/treatment.TreatmentService/ListActCatalog" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ListActCatalogRequest): Buffer =>
      Buffer.from(ListActCatalogRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ListActCatalogRequest => ListActCatalogRequest.decode(value),
    responseSerialize: (value: ActCatalogListReply): Buffer => Buffer.from(ActCatalogListReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): ActCatalogListReply => ActCatalogListReply.decode(value),
  },
  getActCatalog: {
    path: "/treatment.TreatmentService/GetActCatalog" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetActCatalogRequest): Buffer => Buffer.from(GetActCatalogRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetActCatalogRequest => GetActCatalogRequest.decode(value),
    responseSerialize: (value: ActCatalogReply): Buffer => Buffer.from(ActCatalogReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): ActCatalogReply => ActCatalogReply.decode(value),
  },
  createActCatalog: {
    path: "/treatment.TreatmentService/CreateActCatalog" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CreateActCatalogRequest): Buffer =>
      Buffer.from(CreateActCatalogRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateActCatalogRequest => CreateActCatalogRequest.decode(value),
    responseSerialize: (value: ActCatalogReply): Buffer => Buffer.from(ActCatalogReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): ActCatalogReply => ActCatalogReply.decode(value),
  },
  updateActCatalog: {
    path: "/treatment.TreatmentService/UpdateActCatalog" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: UpdateActCatalogRequest): Buffer =>
      Buffer.from(UpdateActCatalogRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UpdateActCatalogRequest => UpdateActCatalogRequest.decode(value),
    responseSerialize: (value: ActCatalogReply): Buffer => Buffer.from(ActCatalogReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): ActCatalogReply => ActCatalogReply.decode(value),
  },
  deleteActCatalog: {
    path: "/treatment.TreatmentService/DeleteActCatalog" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: DeleteActCatalogRequest): Buffer =>
      Buffer.from(DeleteActCatalogRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): DeleteActCatalogRequest => DeleteActCatalogRequest.decode(value),
    responseSerialize: (value: EmptyReply): Buffer => Buffer.from(EmptyReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): EmptyReply => EmptyReply.decode(value),
  },
  listTreatmentActs: {
    path: "/treatment.TreatmentService/ListTreatmentActs" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ListTreatmentActsRequest): Buffer =>
      Buffer.from(ListTreatmentActsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ListTreatmentActsRequest => ListTreatmentActsRequest.decode(value),
    responseSerialize: (value: TreatmentActListReply): Buffer =>
      Buffer.from(TreatmentActListReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): TreatmentActListReply => TreatmentActListReply.decode(value),
  },
  getTreatmentAct: {
    path: "/treatment.TreatmentService/GetTreatmentAct" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetTreatmentActRequest): Buffer =>
      Buffer.from(GetTreatmentActRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetTreatmentActRequest => GetTreatmentActRequest.decode(value),
    responseSerialize: (value: TreatmentActReply): Buffer => Buffer.from(TreatmentActReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): TreatmentActReply => TreatmentActReply.decode(value),
  },
  addTreatmentAct: {
    path: "/treatment.TreatmentService/AddTreatmentAct" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: AddTreatmentActRequest): Buffer =>
      Buffer.from(AddTreatmentActRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): AddTreatmentActRequest => AddTreatmentActRequest.decode(value),
    responseSerialize: (value: TreatmentActReply): Buffer => Buffer.from(TreatmentActReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): TreatmentActReply => TreatmentActReply.decode(value),
  },
  updateTreatmentAct: {
    path: "/treatment.TreatmentService/UpdateTreatmentAct" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: UpdateTreatmentActRequest): Buffer =>
      Buffer.from(UpdateTreatmentActRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UpdateTreatmentActRequest => UpdateTreatmentActRequest.decode(value),
    responseSerialize: (value: TreatmentActReply): Buffer => Buffer.from(TreatmentActReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): TreatmentActReply => TreatmentActReply.decode(value),
  },
  removeTreatmentAct: {
    path: "/treatment.TreatmentService/RemoveTreatmentAct" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: RemoveTreatmentActRequest): Buffer =>
      Buffer.from(RemoveTreatmentActRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): RemoveTreatmentActRequest => RemoveTreatmentActRequest.decode(value),
    responseSerialize: (value: EmptyReply): Buffer => Buffer.from(EmptyReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): EmptyReply => EmptyReply.decode(value),
  },
  calculateVisitTotal: {
    path: "/treatment.TreatmentService/CalculateVisitTotal" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CalculateVisitTotalRequest): Buffer =>
      Buffer.from(CalculateVisitTotalRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CalculateVisitTotalRequest => CalculateVisitTotalRequest.decode(value),
    responseSerialize: (value: VisitTotalReply): Buffer => Buffer.from(VisitTotalReply.encode(value).finish()),
    responseDeserialize: (value: Buffer): VisitTotalReply => VisitTotalReply.decode(value),
  },
} as const;

export interface TreatmentServiceServer extends UntypedServiceImplementation {
  getVisit: handleUnaryCall<GetVisitRequest, VisitReply>;
  getVisitByAppointment: handleUnaryCall<GetVisitByAppointmentRequest, NullableVisitReply>;
  listOpenVisits: handleUnaryCall<ListOpenVisitsRequest, VisitsListReply>;
  openVisit: handleUnaryCall<OpenVisitRequest, VisitReply>;
  assignAssistant: handleUnaryCall<AssignAssistantRequest, VisitReply>;
  confirmVisit: handleUnaryCall<ConfirmVisitRequest, VisitReply>;
  closeVisit: handleUnaryCall<CloseVisitRequest, VisitReply>;
  voidVisit: handleUnaryCall<VoidVisitRequest, VisitReply>;
  listActCatalog: handleUnaryCall<ListActCatalogRequest, ActCatalogListReply>;
  getActCatalog: handleUnaryCall<GetActCatalogRequest, ActCatalogReply>;
  createActCatalog: handleUnaryCall<CreateActCatalogRequest, ActCatalogReply>;
  updateActCatalog: handleUnaryCall<UpdateActCatalogRequest, ActCatalogReply>;
  deleteActCatalog: handleUnaryCall<DeleteActCatalogRequest, EmptyReply>;
  listTreatmentActs: handleUnaryCall<ListTreatmentActsRequest, TreatmentActListReply>;
  getTreatmentAct: handleUnaryCall<GetTreatmentActRequest, TreatmentActReply>;
  addTreatmentAct: handleUnaryCall<AddTreatmentActRequest, TreatmentActReply>;
  updateTreatmentAct: handleUnaryCall<UpdateTreatmentActRequest, TreatmentActReply>;
  removeTreatmentAct: handleUnaryCall<RemoveTreatmentActRequest, EmptyReply>;
  calculateVisitTotal: handleUnaryCall<CalculateVisitTotalRequest, VisitTotalReply>;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
