export const PATIENT_REPOSITORY = "PATIENT_REPOSITORY";
export const INSURANCE_PROVIDER_REPOSITORY = "INSURANCE_PROVIDER_REPOSITORY";
export const INSURANCE_TEMPLATE_REPOSITORY = "INSURANCE_TEMPLATE_REPOSITORY";
export const PATIENT_INSURANCE_REPOSITORY = "PATIENT_INSURANCE_REPOSITORY";
export const PATIENT_DOCUMENT_REPOSITORY = "PATIENT_DOCUMENT_REPOSITORY";
