export const CLINIC_REPOSITORY = "CLINIC_REPOSITORY";
export const WORKING_HOURS_REPOSITORY = "WORKING_HOURS_REPOSITORY";
export const STAFF_MEMBER_REPOSITORY = "STAFF_MEMBER_REPOSITORY";
export const AUTH_SERVICE_CLIENT = "AUTH_SERVICE_CLIENT";
export const AUTH_SERVICE_GRPC_CLIENT = "AUTH_SERVICE_GRPC_CLIENT";
